// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AddPantryItemInput struct {
	Name           string          `json:"name"`
	Quantity       string          `json:"quantity"`
	Location       StorageLocation `json:"location"`
	ExpirationDate string          `json:"expirationDate"`
	Category       string          `json:"category"`
}

type AppPreferences struct {
	WeeklyBudget                         string   `json:"weeklyBudget"`
	PreferredFinanceTopics               []string `json:"preferredFinanceTopics"`
	PreferredResources                   []string `json:"preferredResources"`
	WantsGovAssistance                   bool     `json:"wantsGovAssistance"`
	LastMealPlanDate                     *string  `json:"lastMealPlanDate,omitempty"`
	NotificationsEnabled                 bool     `json:"notificationsEnabled"`
	ExpiringPantryNotificationsEnabled   bool     `json:"expiringPantryNotificationsEnabled"`
	WeeklyMealPlanNotificationsEnabled   bool     `json:"weeklyMealPlanNotificationsEnabled"`
	ResourceReminderNotificationsEnabled bool     `json:"resourceReminderNotificationsEnabled"`
	CreatedAt                            string   `json:"createdAt"`
	UpdatedAt                            string   `json:"updatedAt"`
}

type CompleteOnboardingInput struct {
	Profile     *UpdateProfileInput     `json:"profile,omitempty"`
	Preferences *UpdatePreferencesInput `json:"preferences,omitempty"`
}

type HandleAvailability struct {
	Handle     string                   `json:"handle"`
	Available  bool                     `json:"available"`
	Reason     HandleAvailabilityReason `json:"reason"`
	RetryAfter *string                  `json:"retryAfter,omitempty"`
}

type Mutation struct {
}

type OnboardingState struct {
	HasCompletedOnboarding bool    `json:"hasCompletedOnboarding"`
	CompletedAt            *string `json:"completedAt,omitempty"`
	CreatedAt              string  `json:"createdAt"`
	UpdatedAt              string  `json:"updatedAt"`
}

type PantryItem struct {
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	Quantity       string          `json:"quantity"`
	Location       StorageLocation `json:"location"`
	ExpirationDate string          `json:"expirationDate"`
	Category       string          `json:"category"`
	Status         ItemStatus      `json:"status"`
	DateAdded      string          `json:"dateAdded"`
	DateUsed       *string         `json:"dateUsed,omitempty"`
	CreatedAt      string          `json:"createdAt"`
	UpdatedAt      string          `json:"updatedAt"`
}

type PantryItemFilterInput struct {
	Status   *ItemStatus      `json:"status,omitempty"`
	Location *StorageLocation `json:"location,omitempty"`
}

type Profile struct {
	Handle          *string `json:"handle,omitempty"`
	FirstName       string  `json:"firstName"`
	LastName        string  `json:"lastName"`
	Phone           string  `json:"phone"`
	Zip             string  `json:"zip"`
	HouseholdSize   int     `json:"householdSize"`
	ProfileImageURI *string `json:"profileImageUri,omitempty"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
}

type PushToken struct {
	ID         string       `json:"id"`
	Token      string       `json:"token"`
	Platform   PushPlatform `json:"platform"`
	DeviceID   *string      `json:"deviceId,omitempty"`
	CreatedAt  string       `json:"createdAt"`
	UpdatedAt  string       `json:"updatedAt"`
	LastSeenAt string       `json:"lastSeenAt"`
}

type Query struct {
}

type RegisterPushTokenInput struct {
	Token    string       `json:"token"`
	Platform PushPlatform `json:"platform"`
	DeviceID *string      `json:"deviceId,omitempty"`
}

type UpdatePantryItemInput struct {
	Name           *string          `json:"name,omitempty"`
	Quantity       *string          `json:"quantity,omitempty"`
	Location       *StorageLocation `json:"location,omitempty"`
	ExpirationDate *string          `json:"expirationDate,omitempty"`
	Category       *string          `json:"category,omitempty"`
	Status         *ItemStatus      `json:"status,omitempty"`
}

type UpdatePreferencesInput struct {
	WeeklyBudget                         *string  `json:"weeklyBudget,omitempty"`
	PreferredFinanceTopics               []string `json:"preferredFinanceTopics,omitempty"`
	PreferredResources                   []string `json:"preferredResources,omitempty"`
	WantsGovAssistance                   *bool    `json:"wantsGovAssistance,omitempty"`
	LastMealPlanDate                     *string  `json:"lastMealPlanDate,omitempty"`
	NotificationsEnabled                 *bool    `json:"notificationsEnabled,omitempty"`
	ExpiringPantryNotificationsEnabled   *bool    `json:"expiringPantryNotificationsEnabled,omitempty"`
	WeeklyMealPlanNotificationsEnabled   *bool    `json:"weeklyMealPlanNotificationsEnabled,omitempty"`
	ResourceReminderNotificationsEnabled *bool    `json:"resourceReminderNotificationsEnabled,omitempty"`
}

type UpdateProfileInput struct {
	FirstName       *string `json:"firstName,omitempty"`
	LastName        *string `json:"lastName,omitempty"`
	Phone           *string `json:"phone,omitempty"`
	Zip             *string `json:"zip,omitempty"`
	HouseholdSize   *int    `json:"householdSize,omitempty"`
	ProfileImageURI *string `json:"profileImageUri,omitempty"`
}

type User struct {
	ID          string  `json:"id"`
	AuthSubject string  `json:"authSubject"`
	Email       *string `json:"email,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Viewer struct {
	User            *User            `json:"user"`
	Profile         *Profile         `json:"profile"`
	Preferences     *AppPreferences  `json:"preferences"`
	OnboardingState *OnboardingState `json:"onboardingState"`
}

type WasteStats struct {
	TotalAdded           int      `json:"totalAdded"`
	TotalUsed            int      `json:"totalUsed"`
	TotalExpired         int      `json:"totalExpired"`
	EstimatedWasteValue  float64  `json:"estimatedWasteValue"`
	MostWastedCategories []string `json:"mostWastedCategories"`
}

type HandleAvailabilityReason string

const (
	HandleAvailabilityReasonAvailable     HandleAvailabilityReason = "AVAILABLE"
	HandleAvailabilityReasonCurrent       HandleAvailabilityReason = "CURRENT"
	HandleAvailabilityReasonInvalidFormat HandleAvailabilityReason = "INVALID_FORMAT"
	HandleAvailabilityReasonReserved      HandleAvailabilityReason = "RESERVED"
	HandleAvailabilityReasonUnavailable   HandleAvailabilityReason = "UNAVAILABLE"
	HandleAvailabilityReasonCooldown      HandleAvailabilityReason = "COOLDOWN"
)

var AllHandleAvailabilityReason = []HandleAvailabilityReason{
	HandleAvailabilityReasonAvailable,
	HandleAvailabilityReasonCurrent,
	HandleAvailabilityReasonInvalidFormat,
	HandleAvailabilityReasonReserved,
	HandleAvailabilityReasonUnavailable,
	HandleAvailabilityReasonCooldown,
}

func (e HandleAvailabilityReason) IsValid() bool {
	switch e {
	case HandleAvailabilityReasonAvailable, HandleAvailabilityReasonCurrent, HandleAvailabilityReasonInvalidFormat, HandleAvailabilityReasonReserved, HandleAvailabilityReasonUnavailable, HandleAvailabilityReasonCooldown:
		return true
	}
	return false
}

func (e HandleAvailabilityReason) String() string {
	return string(e)
}

func (e *HandleAvailabilityReason) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HandleAvailabilityReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HandleAvailabilityReason", str)
	}
	return nil
}

func (e HandleAvailabilityReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ItemStatus string

const (
	ItemStatusActive  ItemStatus = "ACTIVE"
	ItemStatusUsed    ItemStatus = "USED"
	ItemStatusExpired ItemStatus = "EXPIRED"
)

var AllItemStatus = []ItemStatus{
	ItemStatusActive,
	ItemStatusUsed,
	ItemStatusExpired,
}

func (e ItemStatus) IsValid() bool {
	switch e {
	case ItemStatusActive, ItemStatusUsed, ItemStatusExpired:
		return true
	}
	return false
}

func (e ItemStatus) String() string {
	return string(e)
}

func (e *ItemStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ItemStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ItemStatus", str)
	}
	return nil
}

func (e ItemStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PushPlatform string

const (
	PushPlatformIos     PushPlatform = "IOS"
	PushPlatformAndroid PushPlatform = "ANDROID"
	PushPlatformWeb     PushPlatform = "WEB"
)

var AllPushPlatform = []PushPlatform{
	PushPlatformIos,
	PushPlatformAndroid,
	PushPlatformWeb,
}

func (e PushPlatform) IsValid() bool {
	switch e {
	case PushPlatformIos, PushPlatformAndroid, PushPlatformWeb:
		return true
	}
	return false
}

func (e PushPlatform) String() string {
	return string(e)
}

func (e *PushPlatform) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PushPlatform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PushPlatform", str)
	}
	return nil
}

func (e PushPlatform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type StorageLocation string

const (
	StorageLocationPantry       StorageLocation = "PANTRY"
	StorageLocationRefrigerator StorageLocation = "REFRIGERATOR"
	StorageLocationFreezer      StorageLocation = "FREEZER"
)

var AllStorageLocation = []StorageLocation{
	StorageLocationPantry,
	StorageLocationRefrigerator,
	StorageLocationFreezer,
}

func (e StorageLocation) IsValid() bool {
	switch e {
	case StorageLocationPantry, StorageLocationRefrigerator, StorageLocationFreezer:
		return true
	}
	return false
}

func (e StorageLocation) String() string {
	return string(e)
}

func (e *StorageLocation) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StorageLocation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StorageLocation", str)
	}
	return nil
}

func (e StorageLocation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
