// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AddPantryItemInput struct {
	Name           string          `json:"name"`
	Quantity       string          `json:"quantity"`
	Location       StorageLocation `json:"location"`
	ExpirationDate string          `json:"expirationDate"`
	Category       string          `json:"category"`
	IngredientID   *string         `json:"ingredientId,omitempty"`
	QuantityAmount *float64        `json:"quantityAmount,omitempty"`
	QuantityUnit   *string         `json:"quantityUnit,omitempty"`
	UseFirst       *bool           `json:"useFirst,omitempty"`
}

type AllergyRequirement struct {
	Allergen Allergen `json:"allergen"`
	Strength Strength `json:"strength"`
}

// Allergies are always required; the server rejects any other strength.
type AllergyRequirementInput struct {
	Allergen Allergen `json:"allergen"`
	Strength Strength `json:"strength"`
}

type AppPreferences struct {
	WeeklyBudget                         string   `json:"weeklyBudget"`
	PreferredFinanceTopics               []string `json:"preferredFinanceTopics"`
	PreferredResources                   []string `json:"preferredResources"`
	WantsGovAssistance                   bool     `json:"wantsGovAssistance"`
	LastMealPlanDate                     *string  `json:"lastMealPlanDate,omitempty"`
	NotificationsEnabled                 bool     `json:"notificationsEnabled"`
	ExpiringPantryNotificationsEnabled   bool     `json:"expiringPantryNotificationsEnabled"`
	WeeklyMealPlanNotificationsEnabled   bool     `json:"weeklyMealPlanNotificationsEnabled"`
	ResourceReminderNotificationsEnabled bool     `json:"resourceReminderNotificationsEnabled"`
	CreatedAt                            string   `json:"createdAt"`
	UpdatedAt                            string   `json:"updatedAt"`
}

type BalancedMealBaseline struct {
	Applied  bool     `json:"applied"`
	AvgScore *float64 `json:"avgScore,omitempty"`
}

// One stored answer.
//
// `status` is the load-bearing field. `PROVIDED` and `NONE` are answers and can
// appear on a form; `UNKNOWN` means nobody has asked and `REFUSED` means they
// declined, and neither is ever written onto an application.
type BenefitsAnswer struct {
	FieldPath   string               `json:"fieldPath"`
	RowID       *string              `json:"rowId,omitempty"`
	Status      BenefitsAnswerStatus `json:"status"`
	Kind        BenefitsValueKind    `json:"kind"`
	Source      BenefitsValueSource  `json:"source"`
	IsSensitive bool                 `json:"isSensitive"`
	Text        *string              `json:"text,omitempty"`
	Number      *float64             `json:"number,omitempty"`
	MoneyCents  *int                 `json:"moneyCents,omitempty"`
	Date        *string              `json:"date,omitempty"`
	Bool        *bool                `json:"bool,omitempty"`
	List        []string             `json:"list,omitempty"`
	// For a sensitive answer this is all that ever comes back — never the value.
	Hint *string `json:"hint,omitempty"`
}

// One answer from the app.
//
// It carries no kind: the server's vocabulary decides what shape each question
// takes, so an answer in the wrong field is rejected rather than stored.
type BenefitsAnswerInput struct {
	FieldPath  string               `json:"fieldPath"`
	Status     BenefitsAnswerStatus `json:"status"`
	Text       *string              `json:"text,omitempty"`
	Number     *float64             `json:"number,omitempty"`
	MoneyCents *int                 `json:"moneyCents,omitempty"`
	Date       *string              `json:"date,omitempty"`
	Bool       *bool                `json:"bool,omitempty"`
	List       []string             `json:"list,omitempty"`
}

type BenefitsApplication struct {
	ID     string                    `json:"id"`
	Form   *BenefitsForm             `json:"form"`
	Status BenefitsApplicationStatus `json:"status"`
	// What will appear on the PDF, in page order. Sensitive values are masked.
	FilledFields []*BenefitsFilledField `json:"filledFields"`
	// What the app must ask for. Non-empty exactly when the status is NEEDS_INPUT.
	MissingFields []*BenefitsMissingField `json:"missingFields"`
	// Answers that exist but cannot be written, for a person to look at.
	Problems []*BenefitsFieldProblem `json:"problems"`
	// Boxes deliberately left blank — signatures, and rows the household does not have.
	SkippedFields []*BenefitsSkippedField `json:"skippedFields"`
	// Path to the draft PDF on this API, or null until one has been rendered.
	// It requires the same bearer token as this query; there is no public link to a
	// document that carries a household's application.
	DraftDocumentPath *string `json:"draftDocumentPath,omitempty"`
	// Path to the approved, flattened PDF. Null until the applicant approves.
	FinalDocumentPath *string `json:"finalDocumentPath,omitempty"`
	CreatedAt         string  `json:"createdAt"`
	UpdatedAt         string  `json:"updatedAt"`
	ApprovedAt        *string `json:"approvedAt,omitempty"`
}

type BenefitsFieldProblem struct {
	FieldID   string  `json:"fieldId"`
	FieldPath *string `json:"fieldPath,omitempty"`
	// Why the value could not be written. Never echoes the value itself.
	Reason string `json:"reason"`
}

// One question the profile can hold, with the wording the app should use.
type BenefitsFieldSpec struct {
	FieldPath   string            `json:"fieldPath"`
	Kind        BenefitsValueKind `json:"kind"`
	Group       string            `json:"group"`
	Label       string            `json:"label"`
	Question    string            `json:"question"`
	Choices     []string          `json:"choices"`
	IsSensitive bool              `json:"isSensitive"`
	IsDerived   bool              `json:"isDerived"`
	IsRepeating bool              `json:"isRepeating"`
}

type BenefitsFilledField struct {
	FieldID   string              `json:"fieldId"`
	Label     string              `json:"label"`
	FieldPath *string             `json:"fieldPath,omitempty"`
	Page      int                 `json:"page"`
	Source    BenefitsValueSource `json:"source"`
	// What will be written. Masked when the answer is sensitive.
	Text        *string `json:"text,omitempty"`
	Checked     *bool   `json:"checked,omitempty"`
	IsCheckbox  bool    `json:"isCheckbox"`
	IsSensitive bool    `json:"isSensitive"`
}

type BenefitsForm struct {
	ID string `json:"id"`
	// Identifies the exact revision: id@version#revision.
	Key          string               `json:"key"`
	Program      string               `json:"program"`
	Country      string               `json:"country"`
	State        *string              `json:"state,omitempty"`
	FormCode     string               `json:"formCode"`
	FormTitle    string               `json:"formTitle"`
	FormVersion  string               `json:"formVersion"`
	Revision     int                  `json:"revision"`
	PageCount    int                  `json:"pageCount"`
	TemplateKind BenefitsTemplateKind `json:"templateKind"`
	AgencyURL    *string              `json:"agencyUrl,omitempty"`
}

type BenefitsGroup struct {
	GroupPath string `json:"groupPath"`
	// Whether this group has been collected at all. False means the household has
	// not been asked, which is not the same as having none — an uncollected group
	// still produces a question.
	Collected bool                `json:"collected"`
	Rows      []*BenefitsGroupRow `json:"rows"`
}

type BenefitsGroupRow struct {
	RowID   string            `json:"rowId"`
	Answers []*BenefitsAnswer `json:"answers"`
}

type BenefitsGroupRowInput struct {
	// Omit to add a new row; pass an existing id to keep that row's identity.
	RowID   *string                `json:"rowId,omitempty"`
	Answers []*BenefitsAnswerInput `json:"answers"`
}

type BenefitsMissingField struct {
	FieldPath string `json:"fieldPath"`
	Label     string `json:"label"`
	// The wording the app should put to the user.
	Question    string                `json:"question"`
	Group       string                `json:"group"`
	AnswerKind  BenefitsValueKind     `json:"answerKind"`
	Choices     []string              `json:"choices"`
	Strength    BenefitsFieldStrength `json:"strength"`
	IsSensitive bool                  `json:"isSensitive"`
	// True for a value the profile computes rather than collects — a household's
	// monthly income total, say. The app must not put it to the user as a question:
	// there is no answer they could give, and answering its inputs is what fills it.
	IsDerived bool `json:"isDerived"`
	// Which boxes on the form are waiting on this one answer.
	FormFieldIds []string `json:"formFieldIds"`
}

type BenefitsProfile struct {
	// The field-path vocabulary these answers were recorded against.
	VocabularyVersion int               `json:"vocabularyVersion"`
	Answers           []*BenefitsAnswer `json:"answers"`
	Groups            []*BenefitsGroup  `json:"groups"`
}

type BenefitsSkippedField struct {
	FieldID string             `json:"fieldId"`
	Reason  BenefitsSkipReason `json:"reason"`
	Note    *string            `json:"note,omitempty"`
}

type Budget struct {
	Amount   float64    `json:"amount"`
	Currency string     `json:"currency"`
	Mode     BudgetMode `json:"mode"`
}

type BudgetInput struct {
	Amount   float64    `json:"amount"`
	Currency string     `json:"currency"`
	Mode     BudgetMode `json:"mode"`
}

type CompleteOnboardingInput struct {
	Profile     *UpdateProfileInput     `json:"profile,omitempty"`
	Preferences *UpdatePreferencesInput `json:"preferences,omitempty"`
}

type CookingTime struct {
	MaxMinutes *int     `json:"maxMinutes,omitempty"`
	Strength   Strength `json:"strength"`
}

type CookingTimeInput struct {
	MaxMinutes *int     `json:"maxMinutes,omitempty"`
	Strength   Strength `json:"strength"`
}

// An estimated cost is always a range with a confidence, never fake precision.
// Budget compliance is checked against `high`.
type CostRange struct {
	Point      float64        `json:"point"`
	Low        float64        `json:"low"`
	High       float64        `json:"high"`
	Confidence DataConfidence `json:"confidence"`
	// Share of the basket priced at each tier, e.g. {"1": 0.4, "3": 0.6}.
	TierMix map[string]interface{} `json:"tierMix,omitempty"`
	Basis   *string                `json:"basis,omitempty"`
}

type DietRequirement struct {
	Diet     Diet     `json:"diet"`
	Strength Strength `json:"strength"`
}

type DietRequirementInput struct {
	Diet     Diet     `json:"diet"`
	Strength Strength `json:"strength"`
}

type FoodPreferences struct {
	Ingredients []string `json:"ingredients"`
	Cuisines    []string `json:"cuisines"`
	FreeText    *string  `json:"freeText,omitempty"`
}

type FoodPreferencesInput struct {
	Ingredients []string `json:"ingredients"`
	Cuisines    []string `json:"cuisines"`
	FreeText    *string  `json:"freeText,omitempty"`
}

// A consolidated grocery line. Items already in the pantry are kept with
// `inPantry: true` and zero cost rather than hidden, so nothing goes missing.
type GroceryItem struct {
	IngredientID string  `json:"ingredientId"`
	DisplayName  string  `json:"displayName"`
	NeededQty    float64 `json:"neededQty"`
	Unit         string  `json:"unit"`
	// null for loose items sold by weight.
	Packages       *int    `json:"packages,omitempty"`
	PackageLabel   *string `json:"packageLabel,omitempty"`
	EstimatedPrice float64 `json:"estimatedPrice"`
	PriceTier      *int    `json:"priceTier,omitempty"`
	InPantry       bool    `json:"inPantry"`
	IsChecked      bool    `json:"isChecked"`
	// Titles of the recipes this line is for.
	UsedBy []string `json:"usedBy"`
}

type GroceryListFromRecipesInput struct {
	RecipeIds     []string `json:"recipeIds"`
	HouseholdSize int      `json:"householdSize"`
	PantryItems   []string `json:"pantryItems"`
}

type GroceryListPayload struct {
	PlanID   *string           `json:"planId,omitempty"`
	Sections []*GrocerySection `json:"sections"`
	Cost     *CostRange        `json:"cost"`
	// The list with everything the viewer already owns removed: only what has to be
	// bought.
	//
	// It sits alongside `sections`, which keeps pantry items visible at a zero
	// estimate. Both are computed from the same basket, so they can never disagree;
	// which one a screen shows is a presentation decision. A shopper who cannot see
	// that the rice is already at home has no way to tell whether it was considered
	// or forgotten, which is why the full list is still the default.
	PurchaseSections []*GrocerySection `json:"purchaseSections"`
	// What the items still to buy add up to.
	PurchaseCost float64 `json:"purchaseCost"`
}

type GrocerySection struct {
	Aisle string         `json:"aisle"`
	Items []*GroceryItem `json:"items"`
}

type HandleAvailability struct {
	Handle     string                   `json:"handle"`
	Available  bool                     `json:"available"`
	Reason     HandleAvailabilityReason `json:"reason"`
	RetryAfter *string                  `json:"retryAfter,omitempty"`
}

type Household struct {
	Size     int  `json:"size"`
	Adults   *int `json:"adults,omitempty"`
	Children *int `json:"children,omitempty"`
	// True when the user picked 8+; size is stored as 8.
	SizeIsPlus bool `json:"sizeIsPlus"`
}

type HouseholdInput struct {
	Size     int  `json:"size"`
	Adults   *int `json:"adults,omitempty"`
	Children *int `json:"children,omitempty"`
	// True when the user picked 8+; size is stored as 8.
	SizeIsPlus bool `json:"sizeIsPlus"`
}

type ImportRecipeFromVideoInput struct {
	// A cooking video link. Supported hosts are decided server-side.
	URL string `json:"url"`
	// Language for the extracted text. Defaults to english.
	Language *string `json:"language,omitempty"`
}

type Ingredient struct {
	IngredientID       string `json:"ingredientId"`
	DisplayName        string `json:"displayName"`
	Aisle              string `json:"aisle"`
	FoodGroup          string `json:"foodGroup"`
	PriceReferenceUnit string `json:"priceReferenceUnit"`
	IsPantryStaple     bool   `json:"isPantryStaple"`
	// salt, pepper and water only: never added to a grocery list.
	AssumedOnHand bool       `json:"assumedOnHand"`
	Allergens     []Allergen `json:"allergens"`
}

// One ingredient line of a recipe. `quantity` is null when the source never
// stated one — it is never invented, and `missingInformation` says so instead.
type IngredientLine struct {
	Position           int      `json:"position"`
	RawText            string   `json:"rawText"`
	IngredientID       *string  `json:"ingredientId,omitempty"`
	DisplayName        *string  `json:"displayName,omitempty"`
	Quantity           *float64 `json:"quantity,omitempty"`
	Unit               *string  `json:"unit,omitempty"`
	Preparation        *string  `json:"preparation,omitempty"`
	Grams              *float64 `json:"grams,omitempty"`
	IsOptional         bool     `json:"isOptional"`
	IsToTaste          bool     `json:"isToTaste"`
	MissingInformation *string  `json:"missingInformation,omitempty"`
}

type InstructionStep struct {
	Step    int    `json:"step"`
	Text    string `json:"text"`
	Minutes *int   `json:"minutes,omitempty"`
}

type MealCounts struct {
	Breakfast int `json:"breakfast"`
	Lunch     int `json:"lunch"`
	Dinner    int `json:"dinner"`
	Snack     int `json:"snack"`
}

type MealCountsInput struct {
	Breakfast int `json:"breakfast"`
	Lunch     int `json:"lunch"`
	Dinner    int `json:"dinner"`
	Snack     int `json:"snack"`
}

type MealPlan struct {
	PlanID      string            `json:"planId"`
	Status      string            `json:"status"`
	Summary     *PlanSummary      `json:"summary"`
	Meals       []*PlannedMeal    `json:"meals"`
	GroceryList []*GrocerySection `json:"groceryList"`
	// AI-written text. Never a source of numbers.
	PennyMessage string       `json:"pennyMessage"`
	SwapOptions  []SwapAction `json:"swapOptions"`
	Assumptions  []string     `json:"assumptions"`
}

type MealPrepPlan struct {
	PrepPlanID string `json:"prepPlanId"`
	PlanID     string `json:"planId"`
	// Hands-on time, not elapsed time.
	TotalActiveMinutes int             `json:"totalActiveMinutes"`
	Tasks              []*MealPrepTask `json:"tasks"`
}

type MealPrepTask struct {
	TaskID        string           `json:"taskId"`
	Position      int              `json:"position"`
	Kind          MealPrepTaskKind `json:"kind"`
	Title         string           `json:"title"`
	Instruction   string           `json:"instruction"`
	ActiveMinutes int              `json:"activeMinutes"`
	// How much to prepare, in the ingredient's own reference unit. Null when the
	// recipes never stated a quantity — it is not invented, and the instruction
	// says so instead.
	PortionAmount *float64 `json:"portionAmount,omitempty"`
	PortionUnit   *string  `json:"portionUnit,omitempty"`
	// Where to keep it. Guidance from the catalogue's food group, not a safety claim.
	Storage       MealPrepStorage `json:"storage"`
	KeepsDays     *int            `json:"keepsDays,omitempty"`
	IngredientIds []string        `json:"ingredientIds"`
	// Which recipes this is for.
	RecipeIds []string `json:"recipeIds"`
	// Which slots this feeds, as "day:mealType".
	ServesSlots []string `json:"servesSlots"`
	IsDone      bool     `json:"isDone"`
}

type MealProfile struct {
	Household *Household `json:"household"`
	// Null when the user has not set a grocery budget.
	Budget *Budget `json:"budget,omitempty"`
	// Meals needed per week, per category.
	Meals *MealCounts `json:"meals"`
	// Days a generated plan should cover.
	Days                int                `json:"days"`
	DietaryRequirements []*DietRequirement `json:"dietaryRequirements"`
	// Always required. The server rejects any other strength rather than downgrading it.
	Allergies []*AllergyRequirement `json:"allergies"`
	// Other allergies the user named, as canonical ingredient ids.
	AllergyIngredients []string               `json:"allergyIngredients"`
	NutritionGoals     []*NutritionPreference `json:"nutritionGoals"`
	Likes              *FoodPreferences       `json:"likes"`
	Dislikes           *FoodPreferences       `json:"dislikes"`
	CookingTime        *CookingTime           `json:"cookingTime"`
	Equipment          []Equipment            `json:"equipment"`
	CookingStyle       []CookingStyle         `json:"cookingStyle"`
	Leftovers          LeftoversPreference    `json:"leftovers"`
	DietaryOtherText   *string                `json:"dietaryOtherText,omitempty"`
	UpdatedAt          string                 `json:"updatedAt"`
}

type MealProfileInput struct {
	Household            *HouseholdInput             `json:"household"`
	Budget               *BudgetInput                `json:"budget,omitempty"`
	Meals                *MealCountsInput            `json:"meals"`
	Days                 int                         `json:"days"`
	DietaryRequirements  []*DietRequirementInput     `json:"dietaryRequirements"`
	Allergies            []*AllergyRequirementInput  `json:"allergies"`
	AllergyIngredients   []string                    `json:"allergyIngredients"`
	NutritionPreferences []*NutritionPreferenceInput `json:"nutritionPreferences"`
	Likes                *FoodPreferencesInput       `json:"likes"`
	Dislikes             *FoodPreferencesInput       `json:"dislikes"`
	CookingTime          *CookingTimeInput           `json:"cookingTime"`
	Equipment            []Equipment                 `json:"equipment"`
	CookingStyle         []CookingStyle              `json:"cookingStyle"`
	Leftovers            LeftoversPreference         `json:"leftovers"`
	DietaryOtherText     *string                     `json:"dietaryOtherText,omitempty"`
}

type MealSlot struct {
	Day      int      `json:"day"`
	MealType MealType `json:"mealType"`
}

type MealSlotInput struct {
	Day      int      `json:"day"`
	MealType MealType `json:"mealType"`
}

type MoveMealInput struct {
	From *MealSlotInput `json:"from"`
	To   *MealSlotInput `json:"to"`
}

type Mutation struct {
}

type NutritionGoalSummary struct {
	Goal        string   `json:"goal"`
	MetBy       int      `json:"metBy"`
	Of          int      `json:"of"`
	AvgProteinG *float64 `json:"avgProteinG,omitempty"`
}

// Per-serving nutrition. Null where the source never stated it.
type NutritionInfo struct {
	Basis        string          `json:"basis"`
	PerServing   bool            `json:"perServing"`
	CaloriesKcal *float64        `json:"caloriesKcal,omitempty"`
	ProteinG     *float64        `json:"proteinG,omitempty"`
	CarbsG       *float64        `json:"carbsG,omitempty"`
	FatG         *float64        `json:"fatG,omitempty"`
	FiberG       *float64        `json:"fiberG,omitempty"`
	SodiumMg     *float64        `json:"sodiumMg,omitempty"`
	CoveragePct  *float64        `json:"coveragePct,omitempty"`
	Confidence   *DataConfidence `json:"confidence,omitempty"`
}

type NutritionPreference struct {
	Goal     NutritionGoal `json:"goal"`
	Strength Strength      `json:"strength"`
}

type NutritionPreferenceInput struct {
	Goal     NutritionGoal `json:"goal"`
	Strength Strength      `json:"strength"`
}

type OnboardingState struct {
	HasCompletedOnboarding bool    `json:"hasCompletedOnboarding"`
	CompletedAt            *string `json:"completedAt,omitempty"`
	CreatedAt              string  `json:"createdAt"`
	UpdatedAt              string  `json:"updatedAt"`
}

type PantryItem struct {
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	Quantity       string          `json:"quantity"`
	Location       StorageLocation `json:"location"`
	ExpirationDate string          `json:"expirationDate"`
	Category       string          `json:"category"`
	Status         ItemStatus      `json:"status"`
	DateAdded      string          `json:"dateAdded"`
	DateUsed       *string         `json:"dateUsed,omitempty"`
	CreatedAt      string          `json:"createdAt"`
	UpdatedAt      string          `json:"updatedAt"`
	// Canonical catalogue id. Null when the item's name could not be resolved —
	// the item is still in the pantry, it simply does not take part in planning.
	IngredientID   *string  `json:"ingredientId,omitempty"`
	QuantityAmount *float64 `json:"quantityAmount,omitempty"`
	QuantityUnit   *string  `json:"quantityUnit,omitempty"`
	// Ranked above other pantry items when a plan is generated.
	UseFirst bool `json:"useFirst"`
}

type PantryItemFilterInput struct {
	Status   *ItemStatus      `json:"status,omitempty"`
	Location *StorageLocation `json:"location,omitempty"`
}

type PlanRequestInput struct {
	QuestionnaireVersion string           `json:"questionnaireVersion"`
	PlanScope            *string          `json:"planScope,omitempty"`
	Household            *HouseholdInput  `json:"household"`
	Meals                *MealCountsInput `json:"meals"`
	Days                 int              `json:"days"`
	Budget               *BudgetInput     `json:"budget"`
	// Canonical ingredient ids, not free text.
	PantryItems         []string                   `json:"pantryItems"`
	DietaryRequirements []*DietRequirementInput    `json:"dietaryRequirements"`
	DietaryOtherText    *string                    `json:"dietaryOtherText,omitempty"`
	Allergies           []*AllergyRequirementInput `json:"allergies"`
	// Other allergies, resolved to ingredient ids before submit.
	AllergyIngredients   []string                    `json:"allergyIngredients"`
	NutritionPreferences []*NutritionPreferenceInput `json:"nutritionPreferences"`
	Likes                *FoodPreferencesInput       `json:"likes"`
	Dislikes             *FoodPreferencesInput       `json:"dislikes"`
	CookingTime          *CookingTimeInput           `json:"cookingTime"`
	Equipment            []Equipment                 `json:"equipment"`
	CookingStyle         []CookingStyle              `json:"cookingStyle"`
	Leftovers            LeftoversPreference         `json:"leftovers"`
	ExcludeRecipeIds     []string                    `json:"excludeRecipeIds"`
	Seed                 *int                        `json:"seed,omitempty"`
}

type PlanSummary struct {
	HouseholdSize int        `json:"householdSize"`
	MealsPlanned  int        `json:"mealsPlanned"`
	Budget        *float64   `json:"budget,omitempty"`
	EstimatedCost *CostRange `json:"estimatedCost"`
	// budget minus estimatedCost.high; null when no budget was set.
	Headroom             *float64              `json:"headroom,omitempty"`
	ConsumedCostTotal    *float64              `json:"consumedCostTotal,omitempty"`
	PantryValueUsed      *float64              `json:"pantryValueUsed,omitempty"`
	PantryItemsUsed      []string              `json:"pantryItemsUsed"`
	NutritionGoal        *NutritionGoalSummary `json:"nutritionGoal,omitempty"`
	BalancedMealBaseline *BalancedMealBaseline `json:"balancedMealBaseline,omitempty"`
}

type PlannedMeal struct {
	Slot                    *MealSlot `json:"slot"`
	RecipeID                string    `json:"recipeId"`
	Title                   string    `json:"title"`
	TotalTimeMinutes        *int      `json:"totalTimeMinutes,omitempty"`
	ScaleFactor             float64   `json:"scaleFactor"`
	ServingsPlanned         float64   `json:"servingsPlanned"`
	ProteinGPerServing      *float64  `json:"proteinGPerServing,omitempty"`
	GoalIndicator           *string   `json:"goalIndicator,omitempty"`
	PantryIngredientsUsed   []string  `json:"pantryIngredientsUsed"`
	IncrementalCheckoutCost *float64  `json:"incrementalCheckoutCost,omitempty"`
	ConsumedCost            *float64  `json:"consumedCost,omitempty"`
	// Penny's one-line explanation, written by the server from computed facts.
	Why *string `json:"why,omitempty"`
}

type Profile struct {
	Handle          *string `json:"handle,omitempty"`
	FirstName       string  `json:"firstName"`
	LastName        string  `json:"lastName"`
	Phone           string  `json:"phone"`
	Zip             string  `json:"zip"`
	HouseholdSize   int     `json:"householdSize"`
	ProfileImageURI *string `json:"profileImageUri,omitempty"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
}

type PushToken struct {
	ID         string       `json:"id"`
	Token      string       `json:"token"`
	Platform   PushPlatform `json:"platform"`
	DeviceID   *string      `json:"deviceId,omitempty"`
	CreatedAt  string       `json:"createdAt"`
	UpdatedAt  string       `json:"updatedAt"`
	LastSeenAt string       `json:"lastSeenAt"`
}

type Query struct {
}

// The Standard HTH Recipe Object. One format for library, AI-generated, imported
// and hand-entered recipes; `sourceType` is a field, not a second type.
type Recipe struct {
	RecipeID string `json:"recipeId"`
	// null for a public library recipe.
	OwnerUserID        *string            `json:"ownerUserId,omitempty"`
	Title              string             `json:"title"`
	Description        *string            `json:"description,omitempty"`
	SourceType         string             `json:"sourceType"`
	SourceURL          *string            `json:"sourceUrl,omitempty"`
	SourceName         *string            `json:"sourceName,omitempty"`
	LicenseID          *string            `json:"licenseId,omitempty"`
	AttributionText    *string            `json:"attributionText,omitempty"`
	Visibility         string             `json:"visibility"`
	ReviewStatus       string             `json:"reviewStatus"`
	Servings           *float64           `json:"servings,omitempty"`
	ServingsConfidence ValueConfidence    `json:"servingsConfidence"`
	ServingSizeText    *string            `json:"servingSizeText,omitempty"`
	Scalable           bool               `json:"scalable"`
	PrepTimeMinutes    *int               `json:"prepTimeMinutes,omitempty"`
	CookTimeMinutes    *int               `json:"cookTimeMinutes,omitempty"`
	TotalTimeMinutes   *int               `json:"totalTimeMinutes,omitempty"`
	TimeConfidence     ValueConfidence    `json:"timeConfidence"`
	MealTypes          []MealType         `json:"mealTypes"`
	Cuisine            *string            `json:"cuisine,omitempty"`
	Difficulty         *int               `json:"difficulty,omitempty"`
	EquipmentRequired  []Equipment        `json:"equipmentRequired"`
	IsComponent        bool               `json:"isComponent"`
	Tags               []string           `json:"tags"`
	Ingredients        []*IngredientLine  `json:"ingredients"`
	Instructions       []*InstructionStep `json:"instructions"`
	Nutrition          *NutritionInfo     `json:"nutrition,omitempty"`
	// Computed server-side. Incomplete recipes stay viewable but are never planned.
	BaseMealPlanEligible bool     `json:"baseMealPlanEligible"`
	MissingInformation   []string `json:"missingInformation"`
}

type RecipeImport struct {
	ImportID  string `json:"importId"`
	SourceURL string `json:"sourceUrl"`
	// youtube, instagram, tiktok — as resolved from the URL.
	SourcePlatform string             `json:"sourcePlatform"`
	Status         RecipeImportStatus `json:"status"`
	// The extracted recipe, once status is `succeeded`. It is a normal Recipe —
	// there is no second recipe shape for imports — and it carries the same
	// `missingInformation` and `baseMealPlanEligible` as any other.
	//
	// Its `recipeId` is the id the recipe will have once accepted, so the draft
	// can be referred to before it is saved.
	Draft *Recipe `json:"draft,omitempty"`
	// Set once the draft has been accepted. Null before that.
	RecipeID *string `json:"recipeId,omitempty"`
	// A named failure, once status is `failed`: UNSUPPORTED_SOURCE,
	// VIDEO_UNAVAILABLE, VIDEO_TOO_LONG, NO_TRANSCRIPT, NO_RECIPE_FOUND,
	// PROVIDER_ERROR. The app turns these into sentences; they are not display text.
	ErrorCode *string `json:"errorCode,omitempty"`
	// Safe to show. Never echoes transcript or video content.
	ErrorMessage *string `json:"errorMessage,omitempty"`
	CreatedAt    string  `json:"createdAt"`
	CompletedAt  *string `json:"completedAt,omitempty"`
}

type RecipeQueryInput struct {
	// Taxonomy ids: OR within a family, AND across families.
	TagIds   []string  `json:"tagIds,omitempty"`
	MealType *MealType `json:"mealType,omitempty"`
	Search   *string   `json:"search,omitempty"`
	Limit    *int      `json:"limit,omitempty"`
}

type RegisterPushTokenInput struct {
	Token    string       `json:"token"`
	Platform PushPlatform `json:"platform"`
	DeviceID *string      `json:"deviceId,omitempty"`
}

type ReplaceMealInput struct {
	Slot     *MealSlotInput `json:"slot"`
	RecipeID string         `json:"recipeId"`
}

type SaveBenefitsGroupInput struct {
	GroupPath string                   `json:"groupPath"`
	Rows      []*BenefitsGroupRowInput `json:"rows"`
}

type SwapMealInput struct {
	Slot       *MealSlotInput `json:"slot"`
	Action     SwapAction     `json:"action"`
	KeepBasket *bool          `json:"keepBasket,omitempty"`
}

type UpdatePantryItemInput struct {
	Name           *string          `json:"name,omitempty"`
	Quantity       *string          `json:"quantity,omitempty"`
	Location       *StorageLocation `json:"location,omitempty"`
	ExpirationDate *string          `json:"expirationDate,omitempty"`
	Category       *string          `json:"category,omitempty"`
	Status         *ItemStatus      `json:"status,omitempty"`
	IngredientID   *string          `json:"ingredientId,omitempty"`
	QuantityAmount *float64         `json:"quantityAmount,omitempty"`
	QuantityUnit   *string          `json:"quantityUnit,omitempty"`
	UseFirst       *bool            `json:"useFirst,omitempty"`
}

type UpdatePreferencesInput struct {
	WeeklyBudget                         *string  `json:"weeklyBudget,omitempty"`
	PreferredFinanceTopics               []string `json:"preferredFinanceTopics,omitempty"`
	PreferredResources                   []string `json:"preferredResources,omitempty"`
	WantsGovAssistance                   *bool    `json:"wantsGovAssistance,omitempty"`
	LastMealPlanDate                     *string  `json:"lastMealPlanDate,omitempty"`
	NotificationsEnabled                 *bool    `json:"notificationsEnabled,omitempty"`
	ExpiringPantryNotificationsEnabled   *bool    `json:"expiringPantryNotificationsEnabled,omitempty"`
	WeeklyMealPlanNotificationsEnabled   *bool    `json:"weeklyMealPlanNotificationsEnabled,omitempty"`
	ResourceReminderNotificationsEnabled *bool    `json:"resourceReminderNotificationsEnabled,omitempty"`
}

type UpdateProfileInput struct {
	FirstName       *string `json:"firstName,omitempty"`
	LastName        *string `json:"lastName,omitempty"`
	Phone           *string `json:"phone,omitempty"`
	Zip             *string `json:"zip,omitempty"`
	HouseholdSize   *int    `json:"householdSize,omitempty"`
	ProfileImageURI *string `json:"profileImageUri,omitempty"`
}

type UpdateServingsInput struct {
	Slot     *MealSlotInput `json:"slot"`
	Servings float64        `json:"servings"`
}

type User struct {
	ID          string  `json:"id"`
	AuthSubject string  `json:"authSubject"`
	Email       *string `json:"email,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Viewer struct {
	User            *User            `json:"user"`
	Profile         *Profile         `json:"profile"`
	Preferences     *AppPreferences  `json:"preferences"`
	OnboardingState *OnboardingState `json:"onboardingState"`
}

type WasteStats struct {
	TotalAdded           int      `json:"totalAdded"`
	TotalUsed            int      `json:"totalUsed"`
	TotalExpired         int      `json:"totalExpired"`
	EstimatedWasteValue  float64  `json:"estimatedWasteValue"`
	MostWastedCategories []string `json:"mostWastedCategories"`
}

type Allergen string

const (
	AllergenMilk      Allergen = "milk"
	AllergenEgg       Allergen = "egg"
	AllergenFish      Allergen = "fish"
	AllergenShellfish Allergen = "shellfish"
	AllergenTreeNut   Allergen = "tree_nut"
	AllergenPeanut    Allergen = "peanut"
	AllergenWheat     Allergen = "wheat"
	AllergenSoy       Allergen = "soy"
	AllergenSesame    Allergen = "sesame"
)

var AllAllergen = []Allergen{
	AllergenMilk,
	AllergenEgg,
	AllergenFish,
	AllergenShellfish,
	AllergenTreeNut,
	AllergenPeanut,
	AllergenWheat,
	AllergenSoy,
	AllergenSesame,
}

func (e Allergen) IsValid() bool {
	switch e {
	case AllergenMilk, AllergenEgg, AllergenFish, AllergenShellfish, AllergenTreeNut, AllergenPeanut, AllergenWheat, AllergenSoy, AllergenSesame:
		return true
	}
	return false
}

func (e Allergen) String() string {
	return string(e)
}

func (e *Allergen) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Allergen(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Allergen", str)
	}
	return nil
}

func (e Allergen) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BenefitsAnswerStatus string

const (
	// Never asked, or skipped. Never written onto a form.
	BenefitsAnswerStatusUnknown  BenefitsAnswerStatus = "UNKNOWN"
	BenefitsAnswerStatusProvided BenefitsAnswerStatus = "PROVIDED"
	// The applicant said they have none of these. A real answer.
	BenefitsAnswerStatusNone BenefitsAnswerStatus = "NONE"
	// Asked, declined to say. Never written onto a form, and not re-asked.
	BenefitsAnswerStatusRefused BenefitsAnswerStatus = "REFUSED"
)

var AllBenefitsAnswerStatus = []BenefitsAnswerStatus{
	BenefitsAnswerStatusUnknown,
	BenefitsAnswerStatusProvided,
	BenefitsAnswerStatusNone,
	BenefitsAnswerStatusRefused,
}

func (e BenefitsAnswerStatus) IsValid() bool {
	switch e {
	case BenefitsAnswerStatusUnknown, BenefitsAnswerStatusProvided, BenefitsAnswerStatusNone, BenefitsAnswerStatusRefused:
		return true
	}
	return false
}

func (e BenefitsAnswerStatus) String() string {
	return string(e)
}

func (e *BenefitsAnswerStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BenefitsAnswerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BenefitsAnswerStatus", str)
	}
	return nil
}

func (e BenefitsAnswerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BenefitsApplicationStatus string

const (
	BenefitsApplicationStatusDraft          BenefitsApplicationStatus = "DRAFT"
	BenefitsApplicationStatusNeedsInput     BenefitsApplicationStatus = "NEEDS_INPUT"
	BenefitsApplicationStatusReadyForReview BenefitsApplicationStatus = "READY_FOR_REVIEW"
	BenefitsApplicationStatusApproved       BenefitsApplicationStatus = "APPROVED"
	BenefitsApplicationStatusSuperseded     BenefitsApplicationStatus = "SUPERSEDED"
)

var AllBenefitsApplicationStatus = []BenefitsApplicationStatus{
	BenefitsApplicationStatusDraft,
	BenefitsApplicationStatusNeedsInput,
	BenefitsApplicationStatusReadyForReview,
	BenefitsApplicationStatusApproved,
	BenefitsApplicationStatusSuperseded,
}

func (e BenefitsApplicationStatus) IsValid() bool {
	switch e {
	case BenefitsApplicationStatusDraft, BenefitsApplicationStatusNeedsInput, BenefitsApplicationStatusReadyForReview, BenefitsApplicationStatusApproved, BenefitsApplicationStatusSuperseded:
		return true
	}
	return false
}

func (e BenefitsApplicationStatus) String() string {
	return string(e)
}

func (e *BenefitsApplicationStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BenefitsApplicationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BenefitsApplicationStatus", str)
	}
	return nil
}

func (e BenefitsApplicationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BenefitsFieldStrength string

const (
	BenefitsFieldStrengthRequired  BenefitsFieldStrength = "REQUIRED"
	BenefitsFieldStrengthPreferred BenefitsFieldStrength = "PREFERRED"
)

var AllBenefitsFieldStrength = []BenefitsFieldStrength{
	BenefitsFieldStrengthRequired,
	BenefitsFieldStrengthPreferred,
}

func (e BenefitsFieldStrength) IsValid() bool {
	switch e {
	case BenefitsFieldStrengthRequired, BenefitsFieldStrengthPreferred:
		return true
	}
	return false
}

func (e BenefitsFieldStrength) String() string {
	return string(e)
}

func (e *BenefitsFieldStrength) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BenefitsFieldStrength(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BenefitsFieldStrength", str)
	}
	return nil
}

func (e BenefitsFieldStrength) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BenefitsSkipReason string

const (
	// Help The Hive must not fill this — a signature, or the date beside one.
	BenefitsSkipReasonPolicy BenefitsSkipReason = "POLICY"
	// A slot for a row the household does not have.
	BenefitsSkipReasonNotApplicable BenefitsSkipReason = "NOT_APPLICABLE"
)

var AllBenefitsSkipReason = []BenefitsSkipReason{
	BenefitsSkipReasonPolicy,
	BenefitsSkipReasonNotApplicable,
}

func (e BenefitsSkipReason) IsValid() bool {
	switch e {
	case BenefitsSkipReasonPolicy, BenefitsSkipReasonNotApplicable:
		return true
	}
	return false
}

func (e BenefitsSkipReason) String() string {
	return string(e)
}

func (e *BenefitsSkipReason) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BenefitsSkipReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BenefitsSkipReason", str)
	}
	return nil
}

func (e BenefitsSkipReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BenefitsTemplateKind string

const (
	BenefitsTemplateKindAcroform BenefitsTemplateKind = "ACROFORM"
	BenefitsTemplateKindFlat     BenefitsTemplateKind = "FLAT"
)

var AllBenefitsTemplateKind = []BenefitsTemplateKind{
	BenefitsTemplateKindAcroform,
	BenefitsTemplateKindFlat,
}

func (e BenefitsTemplateKind) IsValid() bool {
	switch e {
	case BenefitsTemplateKindAcroform, BenefitsTemplateKindFlat:
		return true
	}
	return false
}

func (e BenefitsTemplateKind) String() string {
	return string(e)
}

func (e *BenefitsTemplateKind) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BenefitsTemplateKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BenefitsTemplateKind", str)
	}
	return nil
}

func (e BenefitsTemplateKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BenefitsValueKind string

const (
	BenefitsValueKindText    BenefitsValueKind = "TEXT"
	BenefitsValueKindNumber  BenefitsValueKind = "NUMBER"
	BenefitsValueKindMoney   BenefitsValueKind = "MONEY"
	BenefitsValueKindDate    BenefitsValueKind = "DATE"
	BenefitsValueKindBoolean BenefitsValueKind = "BOOLEAN"
	BenefitsValueKindChoice  BenefitsValueKind = "CHOICE"
	BenefitsValueKindList    BenefitsValueKind = "LIST"
)

var AllBenefitsValueKind = []BenefitsValueKind{
	BenefitsValueKindText,
	BenefitsValueKindNumber,
	BenefitsValueKindMoney,
	BenefitsValueKindDate,
	BenefitsValueKindBoolean,
	BenefitsValueKindChoice,
	BenefitsValueKindList,
}

func (e BenefitsValueKind) IsValid() bool {
	switch e {
	case BenefitsValueKindText, BenefitsValueKindNumber, BenefitsValueKindMoney, BenefitsValueKindDate, BenefitsValueKindBoolean, BenefitsValueKindChoice, BenefitsValueKindList:
		return true
	}
	return false
}

func (e BenefitsValueKind) String() string {
	return string(e)
}

func (e *BenefitsValueKind) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BenefitsValueKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BenefitsValueKind", str)
	}
	return nil
}

func (e BenefitsValueKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BenefitsValueSource string

const (
	BenefitsValueSourceUser    BenefitsValueSource = "USER"
	BenefitsValueSourceProfile BenefitsValueSource = "PROFILE"
	// Computed from provided answers only.
	BenefitsValueSourceDerived BenefitsValueSource = "DERIVED"
	// Written by a reviewed mapping file, not by the applicant.
	BenefitsValueSourceMappingConstant BenefitsValueSource = "MAPPING_CONSTANT"
)

var AllBenefitsValueSource = []BenefitsValueSource{
	BenefitsValueSourceUser,
	BenefitsValueSourceProfile,
	BenefitsValueSourceDerived,
	BenefitsValueSourceMappingConstant,
}

func (e BenefitsValueSource) IsValid() bool {
	switch e {
	case BenefitsValueSourceUser, BenefitsValueSourceProfile, BenefitsValueSourceDerived, BenefitsValueSourceMappingConstant:
		return true
	}
	return false
}

func (e BenefitsValueSource) String() string {
	return string(e)
}

func (e *BenefitsValueSource) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BenefitsValueSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BenefitsValueSource", str)
	}
	return nil
}

func (e BenefitsValueSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BudgetMode string

const (
	BudgetModeLowest   BudgetMode = "lowest"
	BudgetModeBalanced BudgetMode = "balanced"
	BudgetModeVariety  BudgetMode = "variety"
)

var AllBudgetMode = []BudgetMode{
	BudgetModeLowest,
	BudgetModeBalanced,
	BudgetModeVariety,
}

func (e BudgetMode) IsValid() bool {
	switch e {
	case BudgetModeLowest, BudgetModeBalanced, BudgetModeVariety:
		return true
	}
	return false
}

func (e BudgetMode) String() string {
	return string(e)
}

func (e *BudgetMode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BudgetMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BudgetMode", str)
	}
	return nil
}

func (e BudgetMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type CookingStyle string

const (
	CookingStyleQuickEasy       CookingStyle = "quick_easy"
	CookingStyleFewIngredients  CookingStyle = "few_ingredients"
	CookingStyleOnePot          CookingStyle = "one_pot"
	CookingStyleMealPrep        CookingStyle = "meal_prep"
	CookingStyleFamilyFriendly  CookingStyle = "family_friendly"
	CookingStyleKidFriendly     CookingStyle = "kid_friendly"
	CookingStyleFreezerFriendly CookingStyle = "freezer_friendly"
	CookingStyleUseWhatIHave    CookingStyle = "use_what_i_have"
	CookingStyleLowestCost      CookingStyle = "lowest_cost"
	CookingStyleVariety         CookingStyle = "variety"
)

var AllCookingStyle = []CookingStyle{
	CookingStyleQuickEasy,
	CookingStyleFewIngredients,
	CookingStyleOnePot,
	CookingStyleMealPrep,
	CookingStyleFamilyFriendly,
	CookingStyleKidFriendly,
	CookingStyleFreezerFriendly,
	CookingStyleUseWhatIHave,
	CookingStyleLowestCost,
	CookingStyleVariety,
}

func (e CookingStyle) IsValid() bool {
	switch e {
	case CookingStyleQuickEasy, CookingStyleFewIngredients, CookingStyleOnePot, CookingStyleMealPrep, CookingStyleFamilyFriendly, CookingStyleKidFriendly, CookingStyleFreezerFriendly, CookingStyleUseWhatIHave, CookingStyleLowestCost, CookingStyleVariety:
		return true
	}
	return false
}

func (e CookingStyle) String() string {
	return string(e)
}

func (e *CookingStyle) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CookingStyle(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CookingStyle", str)
	}
	return nil
}

func (e CookingStyle) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DataConfidence string

const (
	DataConfidenceHigh   DataConfidence = "high"
	DataConfidenceMedium DataConfidence = "medium"
	DataConfidenceLow    DataConfidence = "low"
)

var AllDataConfidence = []DataConfidence{
	DataConfidenceHigh,
	DataConfidenceMedium,
	DataConfidenceLow,
}

func (e DataConfidence) IsValid() bool {
	switch e {
	case DataConfidenceHigh, DataConfidenceMedium, DataConfidenceLow:
		return true
	}
	return false
}

func (e DataConfidence) String() string {
	return string(e)
}

func (e *DataConfidence) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DataConfidence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DataConfidence", str)
	}
	return nil
}

func (e DataConfidence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Diet string

const (
	DietVegan       Diet = "vegan"
	DietVegetarian  Diet = "vegetarian"
	DietPescatarian Diet = "pescatarian"
	DietGlutenFree  Diet = "gluten_free"
	DietDairyFree   Diet = "dairy_free"
	DietEggFree     Diet = "egg_free"
	DietNutFree     Diet = "nut_free"
)

var AllDiet = []Diet{
	DietVegan,
	DietVegetarian,
	DietPescatarian,
	DietGlutenFree,
	DietDairyFree,
	DietEggFree,
	DietNutFree,
}

func (e Diet) IsValid() bool {
	switch e {
	case DietVegan, DietVegetarian, DietPescatarian, DietGlutenFree, DietDairyFree, DietEggFree, DietNutFree:
		return true
	}
	return false
}

func (e Diet) String() string {
	return string(e)
}

func (e *Diet) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Diet(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Diet", str)
	}
	return nil
}

func (e Diet) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Equipment string

const (
	EquipmentStovetop   Equipment = "stovetop"
	EquipmentOven       Equipment = "oven"
	EquipmentMicrowave  Equipment = "microwave"
	EquipmentGrill      Equipment = "grill"
	EquipmentBlender    Equipment = "blender"
	EquipmentAirFryer   Equipment = "air_fryer"
	EquipmentSlowCooker Equipment = "slow_cooker"
	EquipmentInstantPot Equipment = "instant_pot"
)

var AllEquipment = []Equipment{
	EquipmentStovetop,
	EquipmentOven,
	EquipmentMicrowave,
	EquipmentGrill,
	EquipmentBlender,
	EquipmentAirFryer,
	EquipmentSlowCooker,
	EquipmentInstantPot,
}

func (e Equipment) IsValid() bool {
	switch e {
	case EquipmentStovetop, EquipmentOven, EquipmentMicrowave, EquipmentGrill, EquipmentBlender, EquipmentAirFryer, EquipmentSlowCooker, EquipmentInstantPot:
		return true
	}
	return false
}

func (e Equipment) String() string {
	return string(e)
}

func (e *Equipment) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Equipment(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Equipment", str)
	}
	return nil
}

func (e Equipment) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type HandleAvailabilityReason string

const (
	HandleAvailabilityReasonAvailable     HandleAvailabilityReason = "AVAILABLE"
	HandleAvailabilityReasonCurrent       HandleAvailabilityReason = "CURRENT"
	HandleAvailabilityReasonInvalidFormat HandleAvailabilityReason = "INVALID_FORMAT"
	HandleAvailabilityReasonReserved      HandleAvailabilityReason = "RESERVED"
	HandleAvailabilityReasonUnavailable   HandleAvailabilityReason = "UNAVAILABLE"
	HandleAvailabilityReasonCooldown      HandleAvailabilityReason = "COOLDOWN"
)

var AllHandleAvailabilityReason = []HandleAvailabilityReason{
	HandleAvailabilityReasonAvailable,
	HandleAvailabilityReasonCurrent,
	HandleAvailabilityReasonInvalidFormat,
	HandleAvailabilityReasonReserved,
	HandleAvailabilityReasonUnavailable,
	HandleAvailabilityReasonCooldown,
}

func (e HandleAvailabilityReason) IsValid() bool {
	switch e {
	case HandleAvailabilityReasonAvailable, HandleAvailabilityReasonCurrent, HandleAvailabilityReasonInvalidFormat, HandleAvailabilityReasonReserved, HandleAvailabilityReasonUnavailable, HandleAvailabilityReasonCooldown:
		return true
	}
	return false
}

func (e HandleAvailabilityReason) String() string {
	return string(e)
}

func (e *HandleAvailabilityReason) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HandleAvailabilityReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HandleAvailabilityReason", str)
	}
	return nil
}

func (e HandleAvailabilityReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ItemStatus string

const (
	ItemStatusActive  ItemStatus = "ACTIVE"
	ItemStatusUsed    ItemStatus = "USED"
	ItemStatusExpired ItemStatus = "EXPIRED"
)

var AllItemStatus = []ItemStatus{
	ItemStatusActive,
	ItemStatusUsed,
	ItemStatusExpired,
}

func (e ItemStatus) IsValid() bool {
	switch e {
	case ItemStatusActive, ItemStatusUsed, ItemStatusExpired:
		return true
	}
	return false
}

func (e ItemStatus) String() string {
	return string(e)
}

func (e *ItemStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ItemStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ItemStatus", str)
	}
	return nil
}

func (e ItemStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type LeftoversPreference string

const (
	LeftoversPreferenceYes       LeftoversPreference = "yes"
	LeftoversPreferenceSometimes LeftoversPreference = "sometimes"
	LeftoversPreferenceNo        LeftoversPreference = "no"
)

var AllLeftoversPreference = []LeftoversPreference{
	LeftoversPreferenceYes,
	LeftoversPreferenceSometimes,
	LeftoversPreferenceNo,
}

func (e LeftoversPreference) IsValid() bool {
	switch e {
	case LeftoversPreferenceYes, LeftoversPreferenceSometimes, LeftoversPreferenceNo:
		return true
	}
	return false
}

func (e LeftoversPreference) String() string {
	return string(e)
}

func (e *LeftoversPreference) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LeftoversPreference(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LeftoversPreference", str)
	}
	return nil
}

func (e LeftoversPreference) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MealPrepStorage string

const (
	MealPrepStorageRefrigerate MealPrepStorage = "refrigerate"
	MealPrepStorageFreeze      MealPrepStorage = "freeze"
	MealPrepStoragePantry      MealPrepStorage = "pantry"
)

var AllMealPrepStorage = []MealPrepStorage{
	MealPrepStorageRefrigerate,
	MealPrepStorageFreeze,
	MealPrepStoragePantry,
}

func (e MealPrepStorage) IsValid() bool {
	switch e {
	case MealPrepStorageRefrigerate, MealPrepStorageFreeze, MealPrepStoragePantry:
		return true
	}
	return false
}

func (e MealPrepStorage) String() string {
	return string(e)
}

func (e *MealPrepStorage) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MealPrepStorage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MealPrepStorage", str)
	}
	return nil
}

func (e MealPrepStorage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MealPrepTaskKind string

const (
	// One ingredient prepared once for several meals.
	MealPrepTaskKindBatchIngredient MealPrepTaskKind = "batch_ingredient"
	// A whole recipe cooked once for several servings.
	MealPrepTaskKindBatchCook MealPrepTaskKind = "batch_cook"
)

var AllMealPrepTaskKind = []MealPrepTaskKind{
	MealPrepTaskKindBatchIngredient,
	MealPrepTaskKindBatchCook,
}

func (e MealPrepTaskKind) IsValid() bool {
	switch e {
	case MealPrepTaskKindBatchIngredient, MealPrepTaskKindBatchCook:
		return true
	}
	return false
}

func (e MealPrepTaskKind) String() string {
	return string(e)
}

func (e *MealPrepTaskKind) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MealPrepTaskKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MealPrepTaskKind", str)
	}
	return nil
}

func (e MealPrepTaskKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MealType string

const (
	MealTypeBreakfast MealType = "breakfast"
	MealTypeLunch     MealType = "lunch"
	MealTypeDinner    MealType = "dinner"
	MealTypeSnack     MealType = "snack"
	MealTypeDessert   MealType = "dessert"
	MealTypeSide      MealType = "side"
)

var AllMealType = []MealType{
	MealTypeBreakfast,
	MealTypeLunch,
	MealTypeDinner,
	MealTypeSnack,
	MealTypeDessert,
	MealTypeSide,
}

func (e MealType) IsValid() bool {
	switch e {
	case MealTypeBreakfast, MealTypeLunch, MealTypeDinner, MealTypeSnack, MealTypeDessert, MealTypeSide:
		return true
	}
	return false
}

func (e MealType) String() string {
	return string(e)
}

func (e *MealType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MealType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MealType", str)
	}
	return nil
}

func (e MealType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type NutritionGoal string

const (
	NutritionGoalHighProtein  NutritionGoal = "high_protein"
	NutritionGoalHighFiber    NutritionGoal = "high_fiber"
	NutritionGoalMoreProduce  NutritionGoal = "more_produce"
	NutritionGoalLowerSodium  NutritionGoal = "lower_sodium"
	NutritionGoalLowerCalorie NutritionGoal = "lower_calorie"
	NutritionGoalBalanced     NutritionGoal = "balanced"
)

var AllNutritionGoal = []NutritionGoal{
	NutritionGoalHighProtein,
	NutritionGoalHighFiber,
	NutritionGoalMoreProduce,
	NutritionGoalLowerSodium,
	NutritionGoalLowerCalorie,
	NutritionGoalBalanced,
}

func (e NutritionGoal) IsValid() bool {
	switch e {
	case NutritionGoalHighProtein, NutritionGoalHighFiber, NutritionGoalMoreProduce, NutritionGoalLowerSodium, NutritionGoalLowerCalorie, NutritionGoalBalanced:
		return true
	}
	return false
}

func (e NutritionGoal) String() string {
	return string(e)
}

func (e *NutritionGoal) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NutritionGoal(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NutritionGoal", str)
	}
	return nil
}

func (e NutritionGoal) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PushPlatform string

const (
	PushPlatformIos     PushPlatform = "IOS"
	PushPlatformAndroid PushPlatform = "ANDROID"
	PushPlatformWeb     PushPlatform = "WEB"
)

var AllPushPlatform = []PushPlatform{
	PushPlatformIos,
	PushPlatformAndroid,
	PushPlatformWeb,
}

func (e PushPlatform) IsValid() bool {
	switch e {
	case PushPlatformIos, PushPlatformAndroid, PushPlatformWeb:
		return true
	}
	return false
}

func (e PushPlatform) String() string {
	return string(e)
}

func (e *PushPlatform) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PushPlatform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PushPlatform", str)
	}
	return nil
}

func (e PushPlatform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RecipeImportStatus string

const (
	RecipeImportStatusQueued    RecipeImportStatus = "queued"
	RecipeImportStatusRunning   RecipeImportStatus = "running"
	RecipeImportStatusSucceeded RecipeImportStatus = "succeeded"
	RecipeImportStatusFailed    RecipeImportStatus = "failed"
	RecipeImportStatusCancelled RecipeImportStatus = "cancelled"
)

var AllRecipeImportStatus = []RecipeImportStatus{
	RecipeImportStatusQueued,
	RecipeImportStatusRunning,
	RecipeImportStatusSucceeded,
	RecipeImportStatusFailed,
	RecipeImportStatusCancelled,
}

func (e RecipeImportStatus) IsValid() bool {
	switch e {
	case RecipeImportStatusQueued, RecipeImportStatusRunning, RecipeImportStatusSucceeded, RecipeImportStatusFailed, RecipeImportStatusCancelled:
		return true
	}
	return false
}

func (e RecipeImportStatus) String() string {
	return string(e)
}

func (e *RecipeImportStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecipeImportStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecipeImportStatus", str)
	}
	return nil
}

func (e RecipeImportStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type StorageLocation string

const (
	StorageLocationPantry       StorageLocation = "PANTRY"
	StorageLocationRefrigerator StorageLocation = "REFRIGERATOR"
	StorageLocationFreezer      StorageLocation = "FREEZER"
)

var AllStorageLocation = []StorageLocation{
	StorageLocationPantry,
	StorageLocationRefrigerator,
	StorageLocationFreezer,
}

func (e StorageLocation) IsValid() bool {
	switch e {
	case StorageLocationPantry, StorageLocationRefrigerator, StorageLocationFreezer:
		return true
	}
	return false
}

func (e StorageLocation) String() string {
	return string(e)
}

func (e *StorageLocation) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StorageLocation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StorageLocation", str)
	}
	return nil
}

func (e StorageLocation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Strength string

const (
	StrengthRequired  Strength = "required"
	StrengthPreferred Strength = "preferred"
)

var AllStrength = []Strength{
	StrengthRequired,
	StrengthPreferred,
}

func (e Strength) IsValid() bool {
	switch e {
	case StrengthRequired, StrengthPreferred:
		return true
	}
	return false
}

func (e Strength) String() string {
	return string(e)
}

func (e *Strength) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Strength(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Strength", str)
	}
	return nil
}

func (e Strength) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SwapAction string

const (
	SwapActionSwapSlot       SwapAction = "swap_slot"
	SwapActionCheaper        SwapAction = "cheaper"
	SwapActionHigherProtein  SwapAction = "higher_protein"
	SwapActionFaster         SwapAction = "faster"
	SwapActionDislike        SwapAction = "dislike"
	SwapActionRegenerateWeek SwapAction = "regenerate_week"
)

var AllSwapAction = []SwapAction{
	SwapActionSwapSlot,
	SwapActionCheaper,
	SwapActionHigherProtein,
	SwapActionFaster,
	SwapActionDislike,
	SwapActionRegenerateWeek,
}

func (e SwapAction) IsValid() bool {
	switch e {
	case SwapActionSwapSlot, SwapActionCheaper, SwapActionHigherProtein, SwapActionFaster, SwapActionDislike, SwapActionRegenerateWeek:
		return true
	}
	return false
}

func (e SwapAction) String() string {
	return string(e)
}

func (e *SwapAction) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SwapAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SwapAction", str)
	}
	return nil
}

func (e SwapAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// How a single recipe value was established. `missing` is never guessed away.
type ValueConfidence string

const (
	ValueConfidenceSource   ValueConfidence = "source"
	ValueConfidenceHuman    ValueConfidence = "human"
	ValueConfidenceInferred ValueConfidence = "inferred"
	ValueConfidenceMissing  ValueConfidence = "missing"
)

var AllValueConfidence = []ValueConfidence{
	ValueConfidenceSource,
	ValueConfidenceHuman,
	ValueConfidenceInferred,
	ValueConfidenceMissing,
}

func (e ValueConfidence) IsValid() bool {
	switch e {
	case ValueConfidenceSource, ValueConfidenceHuman, ValueConfidenceInferred, ValueConfidenceMissing:
		return true
	}
	return false
}

func (e ValueConfidence) String() string {
	return string(e)
}

func (e *ValueConfidence) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ValueConfidence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ValueConfidence", str)
	}
	return nil
}

func (e ValueConfidence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
