package benefits

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DocumentStore holds generated PDFs.
//
// A completed benefits application is one of the most sensitive documents a
// person owns: a household roster, an income statement and, on many forms, a
// Social Security number, in one file. So documents are held by the server and
// handed out only through the authenticated route — never a public URL, and
// never a signed object-storage link, which is a shareable capability to read
// somebody's application.
type DocumentStore interface {
	Put(ctx context.Context, key string, data []byte) error
	Get(ctx context.Context, key string) ([]byte, error)
	Delete(ctx context.Context, key string) error
}

// FileDocumentStore keeps documents on local disk. It is what runs today; a
// bucket-backed implementation satisfies the same interface without the service
// changing.
type FileDocumentStore struct {
	root string
}

func NewFileDocumentStore(root string) (*FileDocumentStore, error) {
	if strings.TrimSpace(root) == "" {
		return nil, fmt.Errorf("a document store needs a root directory")
	}
	// 0o700: nothing else on the host has any business reading these.
	if err := os.MkdirAll(root, 0o700); err != nil {
		return nil, err
	}
	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	return &FileDocumentStore{root: absolute}, nil
}

func (s *FileDocumentStore) Put(_ context.Context, key string, data []byte) error {
	path, err := s.path(key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o600)
}

func (s *FileDocumentStore) Get(_ context.Context, key string) ([]byte, error) {
	path, err := s.path(key)
	if err != nil {
		return nil, err
	}
	return os.ReadFile(path)
}

func (s *FileDocumentStore) Delete(_ context.Context, key string) error {
	path, err := s.path(key)
	if err != nil {
		return err
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// path resolves a storage key under the root and refuses anything that would
// escape it. Keys are generated by this package, but a path traversal reaching
// the filesystem is not a thing to leave to convention.
func (s *FileDocumentStore) path(key string) (string, error) {
	if key == "" {
		return "", fmt.Errorf("empty document key")
	}
	cleaned := filepath.Clean(filepath.Join(s.root, key))
	if cleaned != s.root && !strings.HasPrefix(cleaned, s.root+string(filepath.Separator)) {
		return "", fmt.Errorf("document key %q escapes the document store", key)
	}
	return cleaned, nil
}

// documentKey lays documents out by user so an account deletion can be checked
// by eye as well as by query.
func documentKey(userID, applicationID, kind string) string {
	return filepath.Join(userID, applicationID, kind+".pdf")
}

func digestOf(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}
