package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"

	"github.com/helpthehive/server/internal/auth"
	domain "github.com/helpthehive/server/internal/domain/benefits"
	"github.com/helpthehive/server/internal/graphql/model"
)

// SaveBenefitsAnswers is the resolver for the saveBenefitsAnswers field.
func (r *mutationResolver) SaveBenefitsAnswers(ctx context.Context, input []*model.BenefitsAnswerInput) (*model.BenefitsProfile, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.benefits(); err != nil {
		return nil, err
	}
	profile, err := r.Benefits.SaveAnswers(ctx, identity, benefitsAnswerInputs(input))
	if err != nil {
		return nil, benefitsError(err)
	}
	return benefitsProfileModel(profile), nil
}

// SaveBenefitsGroup is the resolver for the saveBenefitsGroup field.
func (r *mutationResolver) SaveBenefitsGroup(ctx context.Context, input model.SaveBenefitsGroupInput) (*model.BenefitsProfile, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.benefits(); err != nil {
		return nil, err
	}
	profile, err := r.Benefits.SaveGroup(ctx, identity, input.GroupPath, benefitsGroupRowInputs(input.Rows))
	if err != nil {
		return nil, benefitsError(err)
	}
	return benefitsProfileModel(profile), nil
}

// StartBenefitsApplication is the resolver for the startBenefitsApplication field.
func (r *mutationResolver) StartBenefitsApplication(ctx context.Context, formID string) (*model.BenefitsApplication, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.benefits(); err != nil {
		return nil, err
	}
	application, err := r.Benefits.StartApplication(ctx, identity, formID)
	if err != nil {
		return nil, benefitsError(err)
	}
	return benefitsApplicationModel(application), nil
}

// RefillBenefitsApplication is the resolver for the refillBenefitsApplication field.
func (r *mutationResolver) RefillBenefitsApplication(ctx context.Context, applicationID string) (*model.BenefitsApplication, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.benefits(); err != nil {
		return nil, err
	}
	application, err := r.Benefits.Refill(ctx, identity, applicationID)
	if err != nil {
		return nil, benefitsError(err)
	}
	return benefitsApplicationModel(application), nil
}

// ApproveBenefitsApplication is the resolver for the approveBenefitsApplication field.
func (r *mutationResolver) ApproveBenefitsApplication(ctx context.Context, applicationID string) (*model.BenefitsApplication, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.benefits(); err != nil {
		return nil, err
	}
	application, err := r.Benefits.Approve(ctx, identity, applicationID)
	if err != nil {
		return nil, benefitsError(err)
	}
	return benefitsApplicationModel(application), nil
}

// DeleteBenefitsApplication is the resolver for the deleteBenefitsApplication field.
func (r *mutationResolver) DeleteBenefitsApplication(ctx context.Context, applicationID string) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	if err := r.benefits(); err != nil {
		return false, err
	}
	deleted, err := r.Benefits.DeleteApplication(ctx, identity, applicationID)
	if err != nil {
		return false, benefitsError(err)
	}
	return deleted, nil
}

// BenefitsProfile is the resolver for the benefitsProfile field.
func (r *queryResolver) BenefitsProfile(ctx context.Context) (*model.BenefitsProfile, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.benefits(); err != nil {
		return nil, err
	}
	profile, err := r.Benefits.Profile(ctx, identity)
	if err != nil {
		return nil, benefitsError(err)
	}
	return benefitsProfileModel(profile), nil
}

// BenefitsForms is the resolver for the benefitsForms field.
func (r *queryResolver) BenefitsForms(ctx context.Context, state *string, program *string) ([]*model.BenefitsForm, error) {
	if err := r.benefits(); err != nil {
		return nil, err
	}
	forms := r.Benefits.Forms(stringValue(state), stringValue(program))
	out := make([]*model.BenefitsForm, 0, len(forms))
	for _, form := range forms {
		out = append(out, benefitsFormModel(form))
	}
	return out, nil
}

// BenefitsForm is the resolver for the benefitsForm field.
func (r *queryResolver) BenefitsForm(ctx context.Context, formID string) (*model.BenefitsForm, error) {
	if err := r.benefits(); err != nil {
		return nil, err
	}
	form, err := r.Benefits.Form(formID)
	if errors.Is(err, domain.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, benefitsError(err)
	}
	return benefitsFormModel(form), nil
}

// BenefitsApplication is the resolver for the benefitsApplication field.
func (r *queryResolver) BenefitsApplication(ctx context.Context, applicationID string) (*model.BenefitsApplication, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.benefits(); err != nil {
		return nil, err
	}
	application, err := r.Benefits.Application(ctx, identity, applicationID)
	// Null rather than an error, matching the rest of the API: an application
	// the viewer may not see is indistinguishable from one that does not exist.
	if errors.Is(err, domain.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, benefitsError(err)
	}
	return benefitsApplicationModel(application), nil
}

// BenefitsApplications is the resolver for the benefitsApplications field.
func (r *queryResolver) BenefitsApplications(ctx context.Context) ([]*model.BenefitsApplication, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.benefits(); err != nil {
		return nil, err
	}
	applications, err := r.Benefits.Applications(ctx, identity)
	if err != nil {
		return nil, benefitsError(err)
	}
	out := make([]*model.BenefitsApplication, 0, len(applications))
	for _, application := range applications {
		out = append(out, benefitsApplicationModel(application))
	}
	return out, nil
}

// BenefitsFieldVocabulary is the resolver for the benefitsFieldVocabulary field.
func (r *queryResolver) BenefitsFieldVocabulary(ctx context.Context) ([]*model.BenefitsFieldSpec, error) {
	return benefitsFieldVocabularyModel(), nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var errBenefitsUnavailable = errors.New("the benefits system is not available on this server")

func (r *Resolver) benefits() error {
	if r.Benefits == nil {
		return errBenefitsUnavailable
	}
	return nil
}
func stringValue(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}
