package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"

	"github.com/helpthehive/server/internal/auth"
	"github.com/helpthehive/server/internal/domain/meals"
	"github.com/helpthehive/server/internal/graphql/model"
)

// RegenerateMealPrepPlan is the resolver for the regenerateMealPrepPlan field.
func (r *mutationResolver) RegenerateMealPrepPlan(ctx context.Context, planID string) (*model.MealPrepPlan, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	prep, err := r.MealPrep.Regenerate(ctx, identity, planID)
	if err != nil {
		return nil, mealError(err)
	}
	return mealPrepPlanModel(prep), nil
}

// SetMealPrepTaskDone is the resolver for the setMealPrepTaskDone field.
func (r *mutationResolver) SetMealPrepTaskDone(ctx context.Context, taskID string, done bool) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	updated, err := r.MealPrep.SetTaskDone(ctx, identity, taskID, done)
	if err != nil {
		return false, mealError(err)
	}
	return updated, nil
}

// MealPrepPlan is the resolver for the mealPrepPlan field.
func (r *queryResolver) MealPrepPlan(ctx context.Context, planID string) (*model.MealPrepPlan, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	prep, err := r.MealPrep.Get(ctx, identity, planID)
	if errors.Is(err, meals.ErrNotFound) {
		// A plan the viewer may not see is absent, not forbidden.
		return nil, nil
	}
	if err != nil {
		return nil, mealError(err)
	}
	if prep == nil {
		return nil, nil
	}
	return mealPrepPlanModel(*prep), nil
}
