package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/helpthehive/server/internal/auth"
	"github.com/helpthehive/server/internal/graphql/model"
)

// ReplaceMeal is the resolver for the replaceMeal field.
func (r *mutationResolver) ReplaceMeal(ctx context.Context, planID string, input model.ReplaceMealInput) (*model.MealPlan, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	plan, err := r.MealPlans.ReplaceMeal(ctx, identity, planID, slotFromInput(input.Slot), input.RecipeID)
	if err != nil {
		return nil, mealError(err)
	}
	return planModel(plan), nil
}

// RegenerateDay is the resolver for the regenerateDay field.
func (r *mutationResolver) RegenerateDay(ctx context.Context, planID string, day int) (*model.MealPlan, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	plan, err := r.MealPlans.RegenerateDay(ctx, identity, planID, day)
	if err != nil {
		return nil, mealError(err)
	}
	return planModel(plan), nil
}

// UpdateServings is the resolver for the updateServings field.
func (r *mutationResolver) UpdateServings(ctx context.Context, planID string, input model.UpdateServingsInput) (*model.MealPlan, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	plan, err := r.MealPlans.UpdateServings(ctx, identity, planID, slotFromInput(input.Slot), input.Servings)
	if err != nil {
		return nil, mealError(err)
	}
	return planModel(plan), nil
}

// SaveMealPlan is the resolver for the saveMealPlan field.
func (r *mutationResolver) SaveMealPlan(ctx context.Context, planID string) (*model.MealPlan, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	plan, err := r.MealPlans.Save(ctx, identity, planID)
	if err != nil {
		return nil, mealError(err)
	}
	return planModel(plan), nil
}

// PantryIngredientIds is the resolver for the pantryIngredientIds field.
func (r *queryResolver) PantryIngredientIds(ctx context.Context) ([]string, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	ids, err := r.Pantry.IngredientIDs(ctx, identity)
	if err != nil {
		return nil, mealError(err)
	}
	if ids == nil {
		return []string{}, nil
	}
	return ids, nil
}
