package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/helpthehive/server/internal/graphql/model"
)

// GenerateMealPlan is the resolver for the generateMealPlan field.
func (r *mutationResolver) GenerateMealPlan(ctx context.Context, input model.PlanRequestInput) (*model.MealPlan, error) {
	panic(fmt.Errorf("not implemented: GenerateMealPlan - generateMealPlan"))
}

// SwapPlannedMeal is the resolver for the swapPlannedMeal field.
func (r *mutationResolver) SwapPlannedMeal(ctx context.Context, planID string, input model.SwapMealInput) (*model.MealPlan, error) {
	panic(fmt.Errorf("not implemented: SwapPlannedMeal - swapPlannedMeal"))
}

// MovePlannedMeal is the resolver for the movePlannedMeal field.
func (r *mutationResolver) MovePlannedMeal(ctx context.Context, planID string, input model.MoveMealInput) (*model.MealPlan, error) {
	panic(fmt.Errorf("not implemented: MovePlannedMeal - movePlannedMeal"))
}

// AcceptMealPlan is the resolver for the acceptMealPlan field.
func (r *mutationResolver) AcceptMealPlan(ctx context.Context, planID string) (*model.GroceryListPayload, error) {
	panic(fmt.Errorf("not implemented: AcceptMealPlan - acceptMealPlan"))
}

// DeleteMealPlan is the resolver for the deleteMealPlan field.
func (r *mutationResolver) DeleteMealPlan(ctx context.Context, planID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteMealPlan - deleteMealPlan"))
}

// SetGroceryItemChecked is the resolver for the setGroceryItemChecked field.
func (r *mutationResolver) SetGroceryItemChecked(ctx context.Context, planID string, ingredientID string, checked bool) (bool, error) {
	panic(fmt.Errorf("not implemented: SetGroceryItemChecked - setGroceryItemChecked"))
}

// GroceryListFromRecipes is the resolver for the groceryListFromRecipes field.
func (r *mutationResolver) GroceryListFromRecipes(ctx context.Context, input model.GroceryListFromRecipesInput) (*model.GroceryListPayload, error) {
	panic(fmt.Errorf("not implemented: GroceryListFromRecipes - groceryListFromRecipes"))
}

// SaveRecipe is the resolver for the saveRecipe field.
func (r *mutationResolver) SaveRecipe(ctx context.Context, recipeID string) (bool, error) {
	panic(fmt.Errorf("not implemented: SaveRecipe - saveRecipe"))
}

// UnsaveRecipe is the resolver for the unsaveRecipe field.
func (r *mutationResolver) UnsaveRecipe(ctx context.Context, recipeID string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnsaveRecipe - unsaveRecipe"))
}

// Recipes is the resolver for the recipes field.
func (r *queryResolver) Recipes(ctx context.Context, query *model.RecipeQueryInput) ([]*model.Recipe, error) {
	panic(fmt.Errorf("not implemented: Recipes - recipes"))
}

// Recipe is the resolver for the recipe field.
func (r *queryResolver) Recipe(ctx context.Context, recipeID string) (*model.Recipe, error) {
	panic(fmt.Errorf("not implemented: Recipe - recipe"))
}

// SavedRecipes is the resolver for the savedRecipes field.
func (r *queryResolver) SavedRecipes(ctx context.Context) ([]*model.Recipe, error) {
	panic(fmt.Errorf("not implemented: SavedRecipes - savedRecipes"))
}

// Ingredients is the resolver for the ingredients field.
func (r *queryResolver) Ingredients(ctx context.Context, search *string, limit *int) ([]*model.Ingredient, error) {
	panic(fmt.Errorf("not implemented: Ingredients - ingredients"))
}

// CurrentMealPlan is the resolver for the currentMealPlan field.
func (r *queryResolver) CurrentMealPlan(ctx context.Context) (*model.MealPlan, error) {
	panic(fmt.Errorf("not implemented: CurrentMealPlan - currentMealPlan"))
}

// MealPlan is the resolver for the mealPlan field.
func (r *queryResolver) MealPlan(ctx context.Context, planID string) (*model.MealPlan, error) {
	panic(fmt.Errorf("not implemented: MealPlan - mealPlan"))
}

// GroceryList is the resolver for the groceryList field.
func (r *queryResolver) GroceryList(ctx context.Context, planID string) (*model.GroceryListPayload, error) {
	panic(fmt.Errorf("not implemented: GroceryList - groceryList"))
}
