package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/helpthehive/server/internal/auth"
	"github.com/helpthehive/server/internal/graphql/model"
)

// SaveMealProfile is the resolver for the saveMealProfile field.
func (r *mutationResolver) SaveMealProfile(ctx context.Context, input model.MealProfileInput) (*model.MealProfile, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	saved, err := r.MealProfiles.Save(ctx, identity, mealProfileFromInput(input))
	if err != nil {
		return nil, mealError(err)
	}
	return mealProfileModel(saved), nil
}

// MealProfile is the resolver for the mealProfile field.
func (r *queryResolver) MealProfile(ctx context.Context) (*model.MealProfile, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	profile, err := r.MealProfiles.Get(ctx, identity)
	if err != nil {
		return nil, mealError(err)
	}
	if profile == nil {
		// Never having answered is a normal state, not an error: it is what an
		// unstarted questionnaire looks like.
		return nil, nil
	}
	return mealProfileModel(*profile), nil
}
