package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"time"

	"github.com/helpthehive/server/internal/auth"
	"github.com/helpthehive/server/internal/db"
	"github.com/helpthehive/server/internal/graphql/generated"
	"github.com/helpthehive/server/internal/graphql/model"
	usersmodule "github.com/helpthehive/server/internal/modules/users"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// DeleteViewerData is the resolver for the deleteViewerData field.
func (r *mutationResolver) DeleteViewerData(ctx context.Context) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	// Generated benefits PDFs are files, not rows, so deleting the user does
	// not remove them: the cascade takes the database record and leaves the
	// household's completed application sitting on disk. They go first, so a
	// failure here stops the deletion rather than half-finishing it.
	if r.Benefits != nil {
		if err := r.Benefits.PurgeDocumentsForViewer(ctx, identity); err != nil {
			return false, err
		}
	}
	return r.Users.DeleteViewer(ctx, identity)
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.Profile, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	profile, err := r.Users.UpdateProfile(ctx, identity, profilePatchFromInput(input))
	if err != nil {
		return nil, err
	}
	return profileModel(profile), nil
}

// UpdateHandle is the resolver for the updateHandle field.
func (r *mutationResolver) UpdateHandle(ctx context.Context, handle string) (*model.Profile, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	profile, err := r.Users.UpdateHandle(ctx, identity, handle)
	if err != nil {
		var handleErr *usersmodule.HandleError
		if errors.As(err, &handleErr) {
			extensions := map[string]any{"code": string(handleErr.Reason), "handle": handleErr.Handle}
			if handleErr.RetryAfter != nil {
				extensions["retryAfter"] = db.FormatTime(*handleErr.RetryAfter)
			}
			return nil, &gqlerror.Error{Message: handleErr.Error(), Extensions: extensions}
		}
		return nil, err
	}
	return profileModel(profile), nil
}

// UpdatePreferences is the resolver for the updatePreferences field.
func (r *mutationResolver) UpdatePreferences(ctx context.Context, input model.UpdatePreferencesInput) (*model.AppPreferences, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	patch, err := preferencesPatchFromInput(input)
	if err != nil {
		return nil, err
	}
	preferences, err := r.Users.UpdatePreferences(ctx, identity, patch, input.EmailMarketingOptIn)
	if err != nil {
		return nil, err
	}
	return preferencesModel(preferences), nil
}

// CompleteOnboarding is the resolver for the completeOnboarding field.
func (r *mutationResolver) CompleteOnboarding(ctx context.Context, input model.CompleteOnboardingInput) (*model.Viewer, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}

	var profilePatch db.ProfilePatch
	hasProfile := input.Profile != nil
	if input.Profile != nil {
		profilePatch = profilePatchFromInput(*input.Profile)
	}

	var preferencesPatch db.PreferencesPatch
	hasPreferences := input.Preferences != nil
	var emailMarketingOptIn *bool
	if input.Preferences != nil {
		preferencesPatch, err = preferencesPatchFromInput(*input.Preferences)
		if err != nil {
			return nil, err
		}
		emailMarketingOptIn = input.Preferences.EmailMarketingOptIn
	}

	viewer, err := r.Users.CompleteOnboarding(ctx, identity, profilePatch, preferencesPatch, hasProfile, hasPreferences, emailMarketingOptIn)
	if err != nil {
		return nil, err
	}
	return r.extendedViewerModel(ctx, identity, viewer)
}

// RecordConsent is the resolver for the recordConsent field.
func (r *mutationResolver) RecordConsent(ctx context.Context, input model.RecordConsentInput) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	if _, err := r.Users.RecordConsent(ctx, identity, input.TermsVersion, input.PrivacyVersion, input.EmailMarketingOptIn); err != nil {
		return false, err
	}
	return true, nil
}

// AddPantryItem is the resolver for the addPantryItem field.
func (r *mutationResolver) AddPantryItem(ctx context.Context, input model.AddPantryItemInput) (*model.PantryItem, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	expirationDate, err := db.ParseDate(input.ExpirationDate)
	if err != nil {
		return nil, err
	}
	item, err := r.Pantry.Add(ctx, identity, db.CreatePantryItemParams{
		Name:           input.Name,
		Quantity:       input.Quantity,
		Location:       string(input.Location),
		ExpirationDate: expirationDate,
		Category:       input.Category,
		// The contract has carried these since meal-actions.graphql; they were
		// being dropped here. An explicit ingredient id from a picker outranks
		// the name-based resolution the service would otherwise do.
		IngredientID:   input.IngredientID,
		QuantityAmount: input.QuantityAmount,
		QuantityUnit:   input.QuantityUnit,
		UseFirst:       input.UseFirst != nil && *input.UseFirst,
	})
	if err != nil {
		return nil, err
	}
	return r.pantryItemModel(item), nil
}

// UpdatePantryItem is the resolver for the updatePantryItem field.
func (r *mutationResolver) UpdatePantryItem(ctx context.Context, id string, input model.UpdatePantryItemInput) (*model.PantryItem, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	patch, err := pantryPatchFromInput(input)
	if err != nil {
		return nil, err
	}
	item, err := r.Pantry.Update(ctx, identity, id, patch)
	if err != nil {
		return nil, err
	}
	return r.pantryItemModel(item), nil
}

// MarkPantryItemUsed is the resolver for the markPantryItemUsed field.
func (r *mutationResolver) MarkPantryItemUsed(ctx context.Context, id string) (*model.PantryItem, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	item, err := r.Pantry.MarkUsed(ctx, identity, id)
	if err != nil {
		return nil, err
	}
	return r.pantryItemModel(item), nil
}

// DeletePantryItem is the resolver for the deletePantryItem field.
func (r *mutationResolver) DeletePantryItem(ctx context.Context, id string) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	return r.Pantry.Delete(ctx, identity, id)
}

// RegisterPushToken is the resolver for the registerPushToken field.
func (r *mutationResolver) RegisterPushToken(ctx context.Context, input model.RegisterPushTokenInput) (*model.PushToken, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	token, err := r.Users.RegisterPushToken(ctx, identity, input.Token, string(input.Platform), input.DeviceID)
	if err != nil {
		return nil, err
	}
	return pushTokenModel(token), nil
}

// DeletePushToken is the resolver for the deletePushToken field.
func (r *mutationResolver) DeletePushToken(ctx context.Context, token string) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	return r.Users.DeletePushToken(ctx, identity, token)
}

// RequestVerificationCode is the resolver for the requestVerificationCode field.
func (r *mutationResolver) RequestVerificationCode(ctx context.Context, input model.RequestVerificationCodeInput) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	purpose := model.VerificationPurposeSignup
	if input.Purpose != nil {
		purpose = *input.Purpose
	}
	if err := r.Users.RequestVerificationCode(ctx, identity, string(input.Method), string(purpose), input.NewEmail, input.NewPhone); err != nil {
		return false, err
	}
	return true, nil
}

// VerifyCode is the resolver for the verifyCode field.
func (r *mutationResolver) VerifyCode(ctx context.Context, code string) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	if err := r.Users.VerifyCode(ctx, identity, code); err != nil {
		return false, err
	}
	return true, nil
}

// SaveQuestionnaire is the resolver for the saveQuestionnaire field.
func (r *mutationResolver) SaveQuestionnaire(ctx context.Context, input model.SaveQuestionnaireInput) (*model.QuestionnaireAnswers, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	answers, err := r.Users.SaveQuestionnaire(ctx, identity, db.QuestionnairePatch{
		WeeklyBudget:  input.WeeklyBudget,
		FinanceTopics: input.FinanceTopics,
		Resources:     input.Resources,
		PrimaryGoal:   input.PrimaryGoal,
		HouseholdSize: input.HouseholdSize,
		IncomeBracket: input.IncomeBracket,
	})
	if err != nil {
		return nil, err
	}
	return questionnaireAnswersModel(answers), nil
}

// SaveOnboardingStep is the resolver for the saveOnboardingStep field.
func (r *mutationResolver) SaveOnboardingStep(ctx context.Context, step string) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	if err := r.Users.SaveOnboardingStep(ctx, identity, step); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateCommunicationConsents is the resolver for the updateCommunicationConsents field.
func (r *mutationResolver) UpdateCommunicationConsents(ctx context.Context, input model.UpdateCommunicationConsentsInput) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	if err := r.Users.UpdateCommunicationConsents(ctx, identity, input.EmailConsent, input.PhoneCallConsent); err != nil {
		return false, err
	}
	return true, nil
}

// SaveLocationFallback is the resolver for the saveLocationFallback field.
func (r *mutationResolver) SaveLocationFallback(ctx context.Context, zip string) (bool, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return false, err
	}
	if err := r.Users.SaveLocationFallback(ctx, identity, zip); err != nil {
		return false, err
	}
	return true, nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.Viewer, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	viewer, err := r.Users.Viewer(ctx, identity)
	if err != nil {
		return nil, err
	}
	return r.extendedViewerModel(ctx, identity, viewer)
}

// HandleAvailability is the resolver for the handleAvailability field.
func (r *queryResolver) HandleAvailability(ctx context.Context, handle string) (*model.HandleAvailability, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	availability, err := r.Users.HandleAvailability(ctx, identity, handle)
	if err != nil {
		return nil, err
	}
	return &model.HandleAvailability{
		Handle:     availability.Handle,
		Available:  availability.Available,
		Reason:     model.HandleAvailabilityReason(availability.Reason),
		RetryAfter: timeStringPtr(availability.RetryAfter),
	}, nil
}

// PantryItems is the resolver for the pantryItems field.
func (r *queryResolver) PantryItems(ctx context.Context, filter *model.PantryItemFilterInput) ([]*model.PantryItem, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	items, err := r.Pantry.List(ctx, identity, pantryFilterFromInput(filter))
	if err != nil {
		return nil, err
	}
	out := make([]*model.PantryItem, 0, len(items))
	for _, item := range items {
		out = append(out, r.pantryItemModel(item))
	}
	return out, nil
}

// PantryWasteStats is the resolver for the pantryWasteStats field.
func (r *queryResolver) PantryWasteStats(ctx context.Context) (*model.WasteStats, error) {
	identity, err := auth.RequireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	stats, err := r.Pantry.WasteStats(ctx, identity)
	if err != nil {
		return nil, err
	}
	return &model.WasteStats{
		TotalAdded:           stats.TotalAdded,
		TotalUsed:            stats.TotalUsed,
		TotalExpired:         stats.TotalExpired,
		EstimatedWasteValue:  stats.EstimatedWasteValue,
		MostWastedCategories: stats.MostWastedCategories,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func profilePatchFromInput(input model.UpdateProfileInput) db.ProfilePatch {
	return db.ProfilePatch{
		FirstName:       input.FirstName,
		LastName:        input.LastName,
		Phone:           input.Phone,
		Zip:             input.Zip,
		HouseholdSize:   input.HouseholdSize,
		ProfileImageURI: input.ProfileImageURI,
	}
}
func preferencesPatchFromInput(input model.UpdatePreferencesInput) (db.PreferencesPatch, error) {
	var lastMealPlanDate *time.Time
	if input.LastMealPlanDate != nil {
		parsed, err := db.ParseDate(*input.LastMealPlanDate)
		if err != nil {
			return db.PreferencesPatch{}, err
		}
		lastMealPlanDate = &parsed
	}

	return db.PreferencesPatch{
		WeeklyBudget:                         input.WeeklyBudget,
		PreferredFinanceTopics:               input.PreferredFinanceTopics,
		PreferredResources:                   input.PreferredResources,
		WantsGovAssistance:                   input.WantsGovAssistance,
		LastMealPlanDate:                     lastMealPlanDate,
		NotificationsEnabled:                 input.NotificationsEnabled,
		ExpiringPantryNotificationsEnabled:   input.ExpiringPantryNotificationsEnabled,
		WeeklyMealPlanNotificationsEnabled:   input.WeeklyMealPlanNotificationsEnabled,
		ResourceReminderNotificationsEnabled: input.ResourceReminderNotificationsEnabled,
		SelectedBenefitPrograms:              input.SelectedBenefitPrograms,
		LocationPermissionStatus:             input.LocationPermissionStatus,
	}, nil
}
func pantryFilterFromInput(input *model.PantryItemFilterInput) db.PantryFilter {
	if input == nil {
		return db.PantryFilter{}
	}
	filter := db.PantryFilter{}
	if input.Status != nil {
		status := string(*input.Status)
		filter.Status = &status
	}
	if input.Location != nil {
		location := string(*input.Location)
		filter.Location = &location
	}
	return filter
}
func pantryPatchFromInput(input model.UpdatePantryItemInput) (db.PantryItemPatch, error) {
	var expirationDate *time.Time
	if input.ExpirationDate != nil {
		parsed, err := db.ParseDate(*input.ExpirationDate)
		if err != nil {
			return db.PantryItemPatch{}, err
		}
		expirationDate = &parsed
	}

	patch := db.PantryItemPatch{
		Name:           input.Name,
		Quantity:       input.Quantity,
		ExpirationDate: expirationDate,
		Category:       input.Category,
		// Also carried by the contract and previously dropped here.
		IngredientID:   input.IngredientID,
		QuantityAmount: input.QuantityAmount,
		QuantityUnit:   input.QuantityUnit,
		UseFirst:       input.UseFirst,
	}
	if input.Location != nil {
		location := string(*input.Location)
		patch.Location = &location
	}
	if input.Status != nil {
		status := string(*input.Status)
		patch.Status = &status
	}
	return patch, nil
}
func viewerModel(viewer db.Viewer) *model.Viewer {
	return &model.Viewer{
		User:            userModel(viewer.User),
		Profile:         profileModel(viewer.Profile),
		Preferences:     preferencesModel(viewer.Preferences),
		OnboardingState: onboardingStateModel(viewer.OnboardingState),
		Consent:         consentModel(viewer.Consent),
	}
}
func userModel(user db.User) *model.User {
	return &model.User{
		ID:          user.ID,
		AuthSubject: user.AuthSubject,
		Email:       user.Email,
		CreatedAt:   db.FormatTime(user.CreatedAt),
		UpdatedAt:   db.FormatTime(user.UpdatedAt),
	}
}
func profileModel(profile db.Profile) *model.Profile {
	return &model.Profile{
		Handle:          profile.Handle,
		FirstName:       profile.FirstName,
		LastName:        profile.LastName,
		Phone:           profile.Phone,
		Zip:             profile.Zip,
		HouseholdSize:   profile.HouseholdSize,
		ProfileImageURI: profile.ProfileImageURI,
		CreatedAt:       db.FormatTime(profile.CreatedAt),
		UpdatedAt:       db.FormatTime(profile.UpdatedAt),
	}
}
func preferencesModel(preferences db.Preferences) *model.AppPreferences {
	return &model.AppPreferences{
		WeeklyBudget:                         preferences.WeeklyBudget,
		PreferredFinanceTopics:               preferences.PreferredFinanceTopics,
		PreferredResources:                   preferences.PreferredResources,
		WantsGovAssistance:                   preferences.WantsGovAssistance,
		LastMealPlanDate:                     dateStringPtr(preferences.LastMealPlanDate),
		NotificationsEnabled:                 preferences.NotificationsEnabled,
		ExpiringPantryNotificationsEnabled:   preferences.ExpiringPantryNotificationsEnabled,
		WeeklyMealPlanNotificationsEnabled:   preferences.WeeklyMealPlanNotificationsEnabled,
		ResourceReminderNotificationsEnabled: preferences.ResourceReminderNotificationsEnabled,
		BenefitsRenewalNotificationsEnabled:  preferences.BenefitsRenewalNotificationsEnabled,
		BenefitsRenewalDiscreetLockScreen:    preferences.BenefitsRenewalDiscreetLockScreen,
		SelectedBenefitPrograms:              preferences.SelectedBenefitPrograms,
		LocationPermissionStatus:             preferences.LocationPermissionStatus,
		CreatedAt:                            db.FormatTime(preferences.CreatedAt),
		UpdatedAt:                            db.FormatTime(preferences.UpdatedAt),
	}
}
func consentModel(consent *db.Consent) *model.Consent {
	if consent == nil {
		return nil
	}
	return &model.Consent{
		TermsVersion:            consent.TermsVersion,
		TermsAcceptedAt:         db.FormatTime(consent.TermsAcceptedAt),
		PrivacyVersion:          consent.PrivacyVersion,
		PrivacyAcceptedAt:       db.FormatTime(consent.PrivacyAcceptedAt),
		EmailMarketingOptIn:     consent.EmailMarketingOptIn,
		EmailMarketingUpdatedAt: db.FormatTime(consent.EmailMarketingUpdatedAt),
	}
}
func onboardingStateModel(onboarding db.OnboardingState) *model.OnboardingState {
	return &model.OnboardingState{
		HasCompletedOnboarding: onboarding.HasCompletedOnboarding,
		CompletedAt:            timeStringPtr(onboarding.CompletedAt),
		CurrentStep:            onboarding.CurrentStep,
		CreatedAt:              db.FormatTime(onboarding.CreatedAt),
		UpdatedAt:              db.FormatTime(onboarding.UpdatedAt),
	}
}
func (r *Resolver) extendedViewerModel(ctx context.Context, identity auth.Identity, viewer db.Viewer) (*model.Viewer, error) {
	result := viewerModel(viewer)
	answers, err := r.Users.QuestionnaireAnswers(ctx, identity)
	if err != nil {
		return nil, err
	}
	result.QuestionnaireAnswers = questionnaireAnswersModel(answers)
	status, err := r.Users.VerificationStatus(ctx, identity)
	if err != nil {
		return nil, err
	}
	result.Verification = verificationStatusModel(status)
	return result, nil
}
func questionnaireAnswersModel(answers db.QuestionnaireAnswers) *model.QuestionnaireAnswers {
	return &model.QuestionnaireAnswers{
		WeeklyBudget:  answers.WeeklyBudget,
		FinanceTopics: answers.FinanceTopics,
		Resources:     answers.Resources,
		PrimaryGoal:   answers.PrimaryGoal,
		HouseholdSize: answers.HouseholdSize,
		IncomeBracket: answers.IncomeBracket,
		UpdatedAt:     db.FormatTime(answers.UpdatedAt),
	}
}
func verificationStatusModel(status db.VerificationStatus) *model.VerificationStatus {
	var method *model.VerificationMethod
	if status.Method != nil {
		// The database stores the lowercase channel ("email"); the
		// contract exposes the enum (EMAIL).
		switch *status.Method {
		case db.VerificationMethodEmail:
			m := model.VerificationMethodEmail
			method = &m
		}
	}
	return &model.VerificationStatus{
		Verified:   status.Verified,
		VerifiedAt: timeStringPtr(status.VerifiedAt),
		Method:     method,
	}
}
func (r *Resolver) pantryItemModel(item db.PantryItem) *model.PantryItem {
	now := time.Now
	if r.Now != nil {
		now = r.Now
	}
	status := model.ItemStatus(db.EffectiveStatus(item, now()))
	return &model.PantryItem{
		ID:             item.ID,
		Name:           item.Name,
		Quantity:       item.Quantity,
		Location:       model.StorageLocation(item.Location),
		ExpirationDate: db.FormatDate(item.ExpirationDate),
		Category:       item.Category,
		Status:         status,
		DateAdded:      db.FormatDate(item.DateAdded),
		DateUsed:       dateStringPtr(item.DateUsed),
		CreatedAt:      db.FormatTime(item.CreatedAt),
		UpdatedAt:      db.FormatTime(item.UpdatedAt),
	}
}
func pushTokenModel(token db.PushToken) *model.PushToken {
	return &model.PushToken{
		ID:         token.ID,
		Token:      token.Token,
		Platform:   model.PushPlatform(token.Platform),
		DeviceID:   token.DeviceID,
		CreatedAt:  db.FormatTime(token.CreatedAt),
		UpdatedAt:  db.FormatTime(token.UpdatedAt),
		LastSeenAt: db.FormatTime(token.LastSeenAt),
	}
}
func dateStringPtr(value *time.Time) *string {
	if value == nil {
		return nil
	}
	formatted := db.FormatDate(*value)
	return &formatted
}
func timeStringPtr(value *time.Time) *string {
	if value == nil {
		return nil
	}
	formatted := db.FormatTime(*value)
	return &formatted
}
