// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: grocery.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGroceryListItems = `-- name: DeleteGroceryListItems :exec
DELETE FROM grocery_list_items WHERE grocery_list_id = $1
`

func (q *Queries) DeleteGroceryListItems(ctx context.Context, groceryListID string) error {
	_, err := q.db.Exec(ctx, deleteGroceryListItems, groceryListID)
	return err
}

const getGroceryListForPlan = `-- name: GetGroceryListForPlan :one
SELECT id, meal_plan_id, user_id, estimated_cost_point, estimated_cost_low, estimated_cost_high, cost_confidence, created_at, updated_at FROM grocery_lists
WHERE meal_plan_id = $1 AND user_id = $2
`

type GetGroceryListForPlanParams struct {
	MealPlanID string `json:"meal_plan_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) GetGroceryListForPlan(ctx context.Context, arg GetGroceryListForPlanParams) (GroceryList, error) {
	row := q.db.QueryRow(ctx, getGroceryListForPlan, arg.MealPlanID, arg.UserID)
	var i GroceryList
	err := row.Scan(
		&i.ID,
		&i.MealPlanID,
		&i.UserID,
		&i.EstimatedCostPoint,
		&i.EstimatedCostLow,
		&i.EstimatedCostHigh,
		&i.CostConfidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGroceryListItem = `-- name: InsertGroceryListItem :exec
INSERT INTO grocery_list_items (
  id, grocery_list_id, ingredient_id, display_name, needed_qty, unit,
  packages, package_label, estimated_price, price_tier, in_pantry, used_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type InsertGroceryListItemParams struct {
	ID             string         `json:"id"`
	GroceryListID  string         `json:"grocery_list_id"`
	IngredientID   string         `json:"ingredient_id"`
	DisplayName    string         `json:"display_name"`
	NeededQty      pgtype.Numeric `json:"needed_qty"`
	Unit           string         `json:"unit"`
	Packages       pgtype.Int4    `json:"packages"`
	PackageLabel   pgtype.Text    `json:"package_label"`
	EstimatedPrice pgtype.Numeric `json:"estimated_price"`
	PriceTier      pgtype.Int4    `json:"price_tier"`
	InPantry       bool           `json:"in_pantry"`
	UsedBy         []string       `json:"used_by"`
}

func (q *Queries) InsertGroceryListItem(ctx context.Context, arg InsertGroceryListItemParams) error {
	_, err := q.db.Exec(ctx, insertGroceryListItem,
		arg.ID,
		arg.GroceryListID,
		arg.IngredientID,
		arg.DisplayName,
		arg.NeededQty,
		arg.Unit,
		arg.Packages,
		arg.PackageLabel,
		arg.EstimatedPrice,
		arg.PriceTier,
		arg.InPantry,
		arg.UsedBy,
	)
	return err
}

const listGroceryListItems = `-- name: ListGroceryListItems :many
SELECT id, grocery_list_id, ingredient_id, display_name, needed_qty, unit, packages, package_label, estimated_price, price_tier, in_pantry, is_checked, used_by FROM grocery_list_items
WHERE grocery_list_id = $1
ORDER BY estimated_price DESC
`

func (q *Queries) ListGroceryListItems(ctx context.Context, groceryListID string) ([]GroceryListItem, error) {
	rows, err := q.db.Query(ctx, listGroceryListItems, groceryListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroceryListItem{}
	for rows.Next() {
		var i GroceryListItem
		if err := rows.Scan(
			&i.ID,
			&i.GroceryListID,
			&i.IngredientID,
			&i.DisplayName,
			&i.NeededQty,
			&i.Unit,
			&i.Packages,
			&i.PackageLabel,
			&i.EstimatedPrice,
			&i.PriceTier,
			&i.InPantry,
			&i.IsChecked,
			&i.UsedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroceryItemChecked = `-- name: SetGroceryItemChecked :one
UPDATE grocery_list_items i
SET is_checked = $1
FROM grocery_lists l
WHERE i.id = $2
  AND l.id = i.grocery_list_id
  AND l.user_id = $3
RETURNING i.id, i.grocery_list_id, i.ingredient_id, i.display_name, i.needed_qty, i.unit, i.packages, i.package_label, i.estimated_price, i.price_tier, i.in_pantry, i.is_checked, i.used_by
`

type SetGroceryItemCheckedParams struct {
	IsChecked bool   `json:"is_checked"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

// Ownership is proved by joining back to the list's user before updating.
func (q *Queries) SetGroceryItemChecked(ctx context.Context, arg SetGroceryItemCheckedParams) (GroceryListItem, error) {
	row := q.db.QueryRow(ctx, setGroceryItemChecked, arg.IsChecked, arg.ID, arg.UserID)
	var i GroceryListItem
	err := row.Scan(
		&i.ID,
		&i.GroceryListID,
		&i.IngredientID,
		&i.DisplayName,
		&i.NeededQty,
		&i.Unit,
		&i.Packages,
		&i.PackageLabel,
		&i.EstimatedPrice,
		&i.PriceTier,
		&i.InPantry,
		&i.IsChecked,
		&i.UsedBy,
	)
	return i, err
}

const upsertGroceryList = `-- name: UpsertGroceryList :one
INSERT INTO grocery_lists (
  id, meal_plan_id, user_id, estimated_cost_point, estimated_cost_low,
  estimated_cost_high, cost_confidence
) VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (meal_plan_id) DO UPDATE SET
  estimated_cost_point = EXCLUDED.estimated_cost_point,
  estimated_cost_low = EXCLUDED.estimated_cost_low,
  estimated_cost_high = EXCLUDED.estimated_cost_high,
  cost_confidence = EXCLUDED.cost_confidence,
  updated_at = now()
RETURNING id, meal_plan_id, user_id, estimated_cost_point, estimated_cost_low, estimated_cost_high, cost_confidence, created_at, updated_at
`

type UpsertGroceryListParams struct {
	ID                 string         `json:"id"`
	MealPlanID         string         `json:"meal_plan_id"`
	UserID             string         `json:"user_id"`
	EstimatedCostPoint pgtype.Numeric `json:"estimated_cost_point"`
	EstimatedCostLow   pgtype.Numeric `json:"estimated_cost_low"`
	EstimatedCostHigh  pgtype.Numeric `json:"estimated_cost_high"`
	CostConfidence     pgtype.Text    `json:"cost_confidence"`
}

func (q *Queries) UpsertGroceryList(ctx context.Context, arg UpsertGroceryListParams) (GroceryList, error) {
	row := q.db.QueryRow(ctx, upsertGroceryList,
		arg.ID,
		arg.MealPlanID,
		arg.UserID,
		arg.EstimatedCostPoint,
		arg.EstimatedCostLow,
		arg.EstimatedCostHigh,
		arg.CostConfidence,
	)
	var i GroceryList
	err := row.Scan(
		&i.ID,
		&i.MealPlanID,
		&i.UserID,
		&i.EstimatedCostPoint,
		&i.EstimatedCostLow,
		&i.EstimatedCostHigh,
		&i.CostConfidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
