// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ingredients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listIngredients = `-- name: ListIngredients :many
SELECT id, display_name, aisle, food_group, parent_ingredient_id, price_reference_unit, is_pantry_staple, assumed_on_hand, contains_meat, contains_poultry, contains_fish, contains_shellfish, contains_dairy, contains_egg, contains_gluten, contains_wheat, contains_soy, contains_peanut, contains_tree_nut, contains_sesame, contains_coconut, is_animal_derived, created_at, updated_at FROM ingredients ORDER BY display_name ASC
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Aisle,
			&i.FoodGroup,
			&i.ParentIngredientID,
			&i.PriceReferenceUnit,
			&i.IsPantryStaple,
			&i.AssumedOnHand,
			&i.ContainsMeat,
			&i.ContainsPoultry,
			&i.ContainsFish,
			&i.ContainsShellfish,
			&i.ContainsDairy,
			&i.ContainsEgg,
			&i.ContainsGluten,
			&i.ContainsWheat,
			&i.ContainsSoy,
			&i.ContainsPeanut,
			&i.ContainsTreeNut,
			&i.ContainsSesame,
			&i.ContainsCoconut,
			&i.IsAnimalDerived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientsByIDs = `-- name: ListIngredientsByIDs :many
SELECT id, display_name, aisle, food_group, parent_ingredient_id, price_reference_unit, is_pantry_staple, assumed_on_hand, contains_meat, contains_poultry, contains_fish, contains_shellfish, contains_dairy, contains_egg, contains_gluten, contains_wheat, contains_soy, contains_peanut, contains_tree_nut, contains_sesame, contains_coconut, is_animal_derived, created_at, updated_at FROM ingredients WHERE id = ANY($1::text[])
`

func (q *Queries) ListIngredientsByIDs(ctx context.Context, ids []string) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredientsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Aisle,
			&i.FoodGroup,
			&i.ParentIngredientID,
			&i.PriceReferenceUnit,
			&i.IsPantryStaple,
			&i.AssumedOnHand,
			&i.ContainsMeat,
			&i.ContainsPoultry,
			&i.ContainsFish,
			&i.ContainsShellfish,
			&i.ContainsDairy,
			&i.ContainsEgg,
			&i.ContainsGluten,
			&i.ContainsWheat,
			&i.ContainsSoy,
			&i.ContainsPeanut,
			&i.ContainsTreeNut,
			&i.ContainsSesame,
			&i.ContainsCoconut,
			&i.IsAnimalDerived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesForIngredients = `-- name: ListPricesForIngredients :many
SELECT DISTINCT ON (ingredient_id) id, ingredient_id, unit_price, package_size, divisible, tier, source, geographic_scope, created_at, updated_at
FROM ingredient_prices
WHERE ingredient_id = ANY($1::text[])
ORDER BY ingredient_id, tier ASC
`

// Best (lowest) tier per ingredient wins; the service falls back to a parent
// ingredient when a child has no price of its own.
func (q *Queries) ListPricesForIngredients(ctx context.Context, ids []string) ([]IngredientPrice, error) {
	rows, err := q.db.Query(ctx, listPricesForIngredients, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngredientPrice{}
	for rows.Next() {
		var i IngredientPrice
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.UnitPrice,
			&i.PackageSize,
			&i.Divisible,
			&i.Tier,
			&i.Source,
			&i.GeographicScope,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchIngredients = `-- name: SearchIngredients :many
SELECT id, display_name, aisle, food_group, parent_ingredient_id, price_reference_unit, is_pantry_staple, assumed_on_hand, contains_meat, contains_poultry, contains_fish, contains_shellfish, contains_dairy, contains_egg, contains_gluten, contains_wheat, contains_soy, contains_peanut, contains_tree_nut, contains_sesame, contains_coconut, is_animal_derived, created_at, updated_at FROM ingredients
WHERE display_name ILIKE '%' || $1::text || '%'
   OR id ILIKE '%' || $1::text || '%'
ORDER BY display_name ASC
LIMIT $2
`

type SearchIngredientsParams struct {
	Query      string `json:"query"`
	LimitCount int32  `json:"limit_count"`
}

func (q *Queries) SearchIngredients(ctx context.Context, arg SearchIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, searchIngredients, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Aisle,
			&i.FoodGroup,
			&i.ParentIngredientID,
			&i.PriceReferenceUnit,
			&i.IsPantryStaple,
			&i.AssumedOnHand,
			&i.ContainsMeat,
			&i.ContainsPoultry,
			&i.ContainsFish,
			&i.ContainsShellfish,
			&i.ContainsDairy,
			&i.ContainsEgg,
			&i.ContainsGluten,
			&i.ContainsWheat,
			&i.ContainsSoy,
			&i.ContainsPeanut,
			&i.ContainsTreeNut,
			&i.ContainsSesame,
			&i.ContainsCoconut,
			&i.IsAnimalDerived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngredient = `-- name: UpsertIngredient :exec
INSERT INTO ingredients (
  id, display_name, aisle, food_group, parent_ingredient_id,
  price_reference_unit, is_pantry_staple, assumed_on_hand,
  contains_meat, contains_poultry, contains_fish, contains_shellfish,
  contains_dairy, contains_egg, contains_gluten, contains_wheat, contains_soy,
  contains_peanut, contains_tree_nut, contains_sesame, contains_coconut,
  is_animal_derived
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  aisle = EXCLUDED.aisle,
  food_group = EXCLUDED.food_group,
  parent_ingredient_id = EXCLUDED.parent_ingredient_id,
  price_reference_unit = EXCLUDED.price_reference_unit,
  updated_at = now()
`

type UpsertIngredientParams struct {
	ID                 string      `json:"id"`
	DisplayName        string      `json:"display_name"`
	Aisle              string      `json:"aisle"`
	FoodGroup          string      `json:"food_group"`
	ParentIngredientID pgtype.Text `json:"parent_ingredient_id"`
	PriceReferenceUnit string      `json:"price_reference_unit"`
	IsPantryStaple     bool        `json:"is_pantry_staple"`
	AssumedOnHand      bool        `json:"assumed_on_hand"`
	ContainsMeat       bool        `json:"contains_meat"`
	ContainsPoultry    bool        `json:"contains_poultry"`
	ContainsFish       bool        `json:"contains_fish"`
	ContainsShellfish  bool        `json:"contains_shellfish"`
	ContainsDairy      bool        `json:"contains_dairy"`
	ContainsEgg        bool        `json:"contains_egg"`
	ContainsGluten     bool        `json:"contains_gluten"`
	ContainsWheat      bool        `json:"contains_wheat"`
	ContainsSoy        bool        `json:"contains_soy"`
	ContainsPeanut     bool        `json:"contains_peanut"`
	ContainsTreeNut    bool        `json:"contains_tree_nut"`
	ContainsSesame     bool        `json:"contains_sesame"`
	ContainsCoconut    bool        `json:"contains_coconut"`
	IsAnimalDerived    bool        `json:"is_animal_derived"`
}

func (q *Queries) UpsertIngredient(ctx context.Context, arg UpsertIngredientParams) error {
	_, err := q.db.Exec(ctx, upsertIngredient,
		arg.ID,
		arg.DisplayName,
		arg.Aisle,
		arg.FoodGroup,
		arg.ParentIngredientID,
		arg.PriceReferenceUnit,
		arg.IsPantryStaple,
		arg.AssumedOnHand,
		arg.ContainsMeat,
		arg.ContainsPoultry,
		arg.ContainsFish,
		arg.ContainsShellfish,
		arg.ContainsDairy,
		arg.ContainsEgg,
		arg.ContainsGluten,
		arg.ContainsWheat,
		arg.ContainsSoy,
		arg.ContainsPeanut,
		arg.ContainsTreeNut,
		arg.ContainsSesame,
		arg.ContainsCoconut,
		arg.IsAnimalDerived,
	)
	return err
}

const upsertIngredientPrice = `-- name: UpsertIngredientPrice :exec
INSERT INTO ingredient_prices (
  id, ingredient_id, unit_price, package_size, divisible, tier, source, geographic_scope
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (ingredient_id, tier, geographic_scope) DO UPDATE SET
  unit_price = EXCLUDED.unit_price,
  package_size = EXCLUDED.package_size,
  divisible = EXCLUDED.divisible,
  source = EXCLUDED.source,
  updated_at = now()
`

type UpsertIngredientPriceParams struct {
	ID              string         `json:"id"`
	IngredientID    string         `json:"ingredient_id"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	PackageSize     pgtype.Numeric `json:"package_size"`
	Divisible       bool           `json:"divisible"`
	Tier            int32          `json:"tier"`
	Source          string         `json:"source"`
	GeographicScope string         `json:"geographic_scope"`
}

func (q *Queries) UpsertIngredientPrice(ctx context.Context, arg UpsertIngredientPriceParams) error {
	_, err := q.db.Exec(ctx, upsertIngredientPrice,
		arg.ID,
		arg.IngredientID,
		arg.UnitPrice,
		arg.PackageSize,
		arg.Divisible,
		arg.Tier,
		arg.Source,
		arg.GeographicScope,
	)
	return err
}
