// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: meal_plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveActiveMealPlans = `-- name: ArchiveActiveMealPlans :exec
UPDATE meal_plans SET status = 'archived', updated_at = now()
WHERE user_id = $1 AND status = 'active'
`

// One active plan per user is enforced by a unique partial index; archive the
// previous one before inserting a replacement.
func (q *Queries) ArchiveActiveMealPlans(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, archiveActiveMealPlans, userID)
	return err
}

const createMealPlan = `-- name: CreateMealPlan :one
INSERT INTO meal_plans (
  id, user_id, status, start_date, days, household_size, request,
  budget_amount, estimated_cost_point, estimated_cost_low, estimated_cost_high,
  cost_confidence, penny_message, assumptions, generation_source, generation_version
) VALUES ($1,$2,'active',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
RETURNING id, user_id, status, start_date, days, household_size, request, budget_amount, estimated_cost_point, estimated_cost_low, estimated_cost_high, cost_confidence, penny_message, assumptions, generation_source, generation_version, created_at, updated_at
`

type CreateMealPlanParams struct {
	ID                 string         `json:"id"`
	UserID             string         `json:"user_id"`
	StartDate          pgtype.Date    `json:"start_date"`
	Days               int32          `json:"days"`
	HouseholdSize      int32          `json:"household_size"`
	Request            []byte         `json:"request"`
	BudgetAmount       pgtype.Numeric `json:"budget_amount"`
	EstimatedCostPoint pgtype.Numeric `json:"estimated_cost_point"`
	EstimatedCostLow   pgtype.Numeric `json:"estimated_cost_low"`
	EstimatedCostHigh  pgtype.Numeric `json:"estimated_cost_high"`
	CostConfidence     pgtype.Text    `json:"cost_confidence"`
	PennyMessage       string         `json:"penny_message"`
	Assumptions        []string       `json:"assumptions"`
	GenerationSource   string         `json:"generation_source"`
	GenerationVersion  string         `json:"generation_version"`
}

func (q *Queries) CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, createMealPlan,
		arg.ID,
		arg.UserID,
		arg.StartDate,
		arg.Days,
		arg.HouseholdSize,
		arg.Request,
		arg.BudgetAmount,
		arg.EstimatedCostPoint,
		arg.EstimatedCostLow,
		arg.EstimatedCostHigh,
		arg.CostConfidence,
		arg.PennyMessage,
		arg.Assumptions,
		arg.GenerationSource,
		arg.GenerationVersion,
	)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StartDate,
		&i.Days,
		&i.HouseholdSize,
		&i.Request,
		&i.BudgetAmount,
		&i.EstimatedCostPoint,
		&i.EstimatedCostLow,
		&i.EstimatedCostHigh,
		&i.CostConfidence,
		&i.PennyMessage,
		&i.Assumptions,
		&i.GenerationSource,
		&i.GenerationVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMealPlanForUser = `-- name: DeleteMealPlanForUser :exec
DELETE FROM meal_plans WHERE id = $1 AND user_id = $2
`

type DeleteMealPlanForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteMealPlanForUser(ctx context.Context, arg DeleteMealPlanForUserParams) error {
	_, err := q.db.Exec(ctx, deleteMealPlanForUser, arg.ID, arg.UserID)
	return err
}

const deleteMealPlanMeals = `-- name: DeleteMealPlanMeals :exec
DELETE FROM meal_plan_meals WHERE meal_plan_id = $1
`

func (q *Queries) DeleteMealPlanMeals(ctx context.Context, mealPlanID string) error {
	_, err := q.db.Exec(ctx, deleteMealPlanMeals, mealPlanID)
	return err
}

const getActiveMealPlan = `-- name: GetActiveMealPlan :one
SELECT id, user_id, status, start_date, days, household_size, request, budget_amount, estimated_cost_point, estimated_cost_low, estimated_cost_high, cost_confidence, penny_message, assumptions, generation_source, generation_version, created_at, updated_at FROM meal_plans
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveMealPlan(ctx context.Context, userID string) (MealPlan, error) {
	row := q.db.QueryRow(ctx, getActiveMealPlan, userID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StartDate,
		&i.Days,
		&i.HouseholdSize,
		&i.Request,
		&i.BudgetAmount,
		&i.EstimatedCostPoint,
		&i.EstimatedCostLow,
		&i.EstimatedCostHigh,
		&i.CostConfidence,
		&i.PennyMessage,
		&i.Assumptions,
		&i.GenerationSource,
		&i.GenerationVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealPlanForUser = `-- name: GetMealPlanForUser :one
SELECT id, user_id, status, start_date, days, household_size, request, budget_amount, estimated_cost_point, estimated_cost_low, estimated_cost_high, cost_confidence, penny_message, assumptions, generation_source, generation_version, created_at, updated_at FROM meal_plans
WHERE id = $1 AND user_id = $2
`

type GetMealPlanForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// Ownership is enforced here, in SQL, not by filtering in the client.
func (q *Queries) GetMealPlanForUser(ctx context.Context, arg GetMealPlanForUserParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, getMealPlanForUser, arg.ID, arg.UserID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StartDate,
		&i.Days,
		&i.HouseholdSize,
		&i.Request,
		&i.BudgetAmount,
		&i.EstimatedCostPoint,
		&i.EstimatedCostLow,
		&i.EstimatedCostHigh,
		&i.CostConfidence,
		&i.PennyMessage,
		&i.Assumptions,
		&i.GenerationSource,
		&i.GenerationVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealPlanMeal = `-- name: GetMealPlanMeal :one
SELECT m.id, m.meal_plan_id, m.day, m.meal_type, m.recipe_id, m.scale_factor, m.servings_planned, m.pantry_ingredient_ids, m.consumed_cost, m.why FROM meal_plan_meals m
JOIN meal_plans p ON p.id = m.meal_plan_id
WHERE m.meal_plan_id = $1
  AND m.day = $2
  AND m.meal_type = $3
  AND p.user_id = $4
`

type GetMealPlanMealParams struct {
	MealPlanID string `json:"meal_plan_id"`
	Day        int32  `json:"day"`
	MealType   string `json:"meal_type"`
	UserID     string `json:"user_id"`
}

func (q *Queries) GetMealPlanMeal(ctx context.Context, arg GetMealPlanMealParams) (MealPlanMeal, error) {
	row := q.db.QueryRow(ctx, getMealPlanMeal,
		arg.MealPlanID,
		arg.Day,
		arg.MealType,
		arg.UserID,
	)
	var i MealPlanMeal
	err := row.Scan(
		&i.ID,
		&i.MealPlanID,
		&i.Day,
		&i.MealType,
		&i.RecipeID,
		&i.ScaleFactor,
		&i.ServingsPlanned,
		&i.PantryIngredientIds,
		&i.ConsumedCost,
		&i.Why,
	)
	return i, err
}

const insertMealPlanMeal = `-- name: InsertMealPlanMeal :exec
INSERT INTO meal_plan_meals (
  id, meal_plan_id, day, meal_type, recipe_id, scale_factor,
  servings_planned, pantry_ingredient_ids, consumed_cost, why
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertMealPlanMealParams struct {
	ID                  string         `json:"id"`
	MealPlanID          string         `json:"meal_plan_id"`
	Day                 int32          `json:"day"`
	MealType            string         `json:"meal_type"`
	RecipeID            string         `json:"recipe_id"`
	ScaleFactor         pgtype.Numeric `json:"scale_factor"`
	ServingsPlanned     pgtype.Numeric `json:"servings_planned"`
	PantryIngredientIds []string       `json:"pantry_ingredient_ids"`
	ConsumedCost        pgtype.Numeric `json:"consumed_cost"`
	Why                 pgtype.Text    `json:"why"`
}

func (q *Queries) InsertMealPlanMeal(ctx context.Context, arg InsertMealPlanMealParams) error {
	_, err := q.db.Exec(ctx, insertMealPlanMeal,
		arg.ID,
		arg.MealPlanID,
		arg.Day,
		arg.MealType,
		arg.RecipeID,
		arg.ScaleFactor,
		arg.ServingsPlanned,
		arg.PantryIngredientIds,
		arg.ConsumedCost,
		arg.Why,
	)
	return err
}

const listMealPlanMeals = `-- name: ListMealPlanMeals :many
SELECT id, meal_plan_id, day, meal_type, recipe_id, scale_factor, servings_planned, pantry_ingredient_ids, consumed_cost, why FROM meal_plan_meals
WHERE meal_plan_id = $1
ORDER BY day ASC, meal_type ASC
`

func (q *Queries) ListMealPlanMeals(ctx context.Context, mealPlanID string) ([]MealPlanMeal, error) {
	rows, err := q.db.Query(ctx, listMealPlanMeals, mealPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealPlanMeal{}
	for rows.Next() {
		var i MealPlanMeal
		if err := rows.Scan(
			&i.ID,
			&i.MealPlanID,
			&i.Day,
			&i.MealType,
			&i.RecipeID,
			&i.ScaleFactor,
			&i.ServingsPlanned,
			&i.PantryIngredientIds,
			&i.ConsumedCost,
			&i.Why,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlansForUser = `-- name: ListMealPlansForUser :many
SELECT id, user_id, status, start_date, days, household_size, request, budget_amount, estimated_cost_point, estimated_cost_low, estimated_cost_high, cost_confidence, penny_message, assumptions, generation_source, generation_version, created_at, updated_at FROM meal_plans
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListMealPlansForUserParams struct {
	UserID     string `json:"user_id"`
	LimitCount int32  `json:"limit_count"`
}

func (q *Queries) ListMealPlansForUser(ctx context.Context, arg ListMealPlansForUserParams) ([]MealPlan, error) {
	rows, err := q.db.Query(ctx, listMealPlansForUser, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealPlan{}
	for rows.Next() {
		var i MealPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.StartDate,
			&i.Days,
			&i.HouseholdSize,
			&i.Request,
			&i.BudgetAmount,
			&i.EstimatedCostPoint,
			&i.EstimatedCostLow,
			&i.EstimatedCostHigh,
			&i.CostConfidence,
			&i.PennyMessage,
			&i.Assumptions,
			&i.GenerationSource,
			&i.GenerationVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveMealPlanMeal = `-- name: MoveMealPlanMeal :exec
UPDATE meal_plan_meals
SET day = $1, meal_type = $2
WHERE id = $3
`

type MoveMealPlanMealParams struct {
	ToDay      int32  `json:"to_day"`
	ToMealType string `json:"to_meal_type"`
	ID         string `json:"id"`
}

// Reassigns a slot. The basket is unchanged, so no cost is recalculated —
// moving a meal must never behave like a regeneration.
func (q *Queries) MoveMealPlanMeal(ctx context.Context, arg MoveMealPlanMealParams) error {
	_, err := q.db.Exec(ctx, moveMealPlanMeal, arg.ToDay, arg.ToMealType, arg.ID)
	return err
}

const replaceMealPlanMealRecipe = `-- name: ReplaceMealPlanMealRecipe :exec
UPDATE meal_plan_meals
SET recipe_id = $1,
    scale_factor = $2,
    servings_planned = $3,
    pantry_ingredient_ids = $4,
    why = $5
WHERE id = $6
`

type ReplaceMealPlanMealRecipeParams struct {
	RecipeID            string         `json:"recipe_id"`
	ScaleFactor         pgtype.Numeric `json:"scale_factor"`
	ServingsPlanned     pgtype.Numeric `json:"servings_planned"`
	PantryIngredientIds []string       `json:"pantry_ingredient_ids"`
	Why                 pgtype.Text    `json:"why"`
	ID                  string         `json:"id"`
}

func (q *Queries) ReplaceMealPlanMealRecipe(ctx context.Context, arg ReplaceMealPlanMealRecipeParams) error {
	_, err := q.db.Exec(ctx, replaceMealPlanMealRecipe,
		arg.RecipeID,
		arg.ScaleFactor,
		arg.ServingsPlanned,
		arg.PantryIngredientIds,
		arg.Why,
		arg.ID,
	)
	return err
}

const updateMealPlanCost = `-- name: UpdateMealPlanCost :one
UPDATE meal_plans
SET estimated_cost_point = $2,
    estimated_cost_low = $3,
    estimated_cost_high = $4,
    cost_confidence = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, status, start_date, days, household_size, request, budget_amount, estimated_cost_point, estimated_cost_low, estimated_cost_high, cost_confidence, penny_message, assumptions, generation_source, generation_version, created_at, updated_at
`

type UpdateMealPlanCostParams struct {
	ID                 string         `json:"id"`
	EstimatedCostPoint pgtype.Numeric `json:"estimated_cost_point"`
	EstimatedCostLow   pgtype.Numeric `json:"estimated_cost_low"`
	EstimatedCostHigh  pgtype.Numeric `json:"estimated_cost_high"`
	CostConfidence     pgtype.Text    `json:"cost_confidence"`
}

func (q *Queries) UpdateMealPlanCost(ctx context.Context, arg UpdateMealPlanCostParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, updateMealPlanCost,
		arg.ID,
		arg.EstimatedCostPoint,
		arg.EstimatedCostLow,
		arg.EstimatedCostHigh,
		arg.CostConfidence,
	)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StartDate,
		&i.Days,
		&i.HouseholdSize,
		&i.Request,
		&i.BudgetAmount,
		&i.EstimatedCostPoint,
		&i.EstimatedCostLow,
		&i.EstimatedCostHigh,
		&i.CostConfidence,
		&i.PennyMessage,
		&i.Assumptions,
		&i.GenerationSource,
		&i.GenerationVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
