// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OnboardingState struct {
	UserID                 string             `json:"user_id"`
	HasCompletedOnboarding bool               `json:"has_completed_onboarding"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type PantryItem struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Name           string             `json:"name"`
	Quantity       string             `json:"quantity"`
	Location       string             `json:"location"`
	ExpirationDate pgtype.Date        `json:"expiration_date"`
	Category       string             `json:"category"`
	Status         string             `json:"status"`
	DateAdded      pgtype.Date        `json:"date_added"`
	DateUsed       pgtype.Date        `json:"date_used"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Preference struct {
	UserID                               string             `json:"user_id"`
	WeeklyBudget                         string             `json:"weekly_budget"`
	PreferredFinanceTopics               []string           `json:"preferred_finance_topics"`
	PreferredResources                   []string           `json:"preferred_resources"`
	WantsGovAssistance                   bool               `json:"wants_gov_assistance"`
	LastMealPlanDate                     pgtype.Date        `json:"last_meal_plan_date"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	NotificationsEnabled                 bool               `json:"notifications_enabled"`
	ExpiringPantryNotificationsEnabled   bool               `json:"expiring_pantry_notifications_enabled"`
	WeeklyMealPlanNotificationsEnabled   bool               `json:"weekly_meal_plan_notifications_enabled"`
	ResourceReminderNotificationsEnabled bool               `json:"resource_reminder_notifications_enabled"`
}

type Profile struct {
	UserID          string             `json:"user_id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Phone           string             `json:"phone"`
	Zip             string             `json:"zip"`
	HouseholdSize   int32              `json:"household_size"`
	ProfileImageUri pgtype.Text        `json:"profile_image_uri"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProfileHandle struct {
	Handle    string             `json:"handle"`
	UserID    string             `json:"user_id"`
	IsCurrent bool               `json:"is_current"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RetiredAt pgtype.Timestamptz `json:"retired_at"`
}

type PushToken struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Token      string             `json:"token"`
	Platform   string             `json:"platform"`
	DeviceID   pgtype.Text        `json:"device_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type User struct {
	ID          string             `json:"id"`
	AuthSubject string             `json:"auth_subject"`
	Email       pgtype.Text        `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
