// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GroceryList struct {
	ID                 string             `json:"id"`
	MealPlanID         string             `json:"meal_plan_id"`
	UserID             string             `json:"user_id"`
	EstimatedCostPoint pgtype.Numeric     `json:"estimated_cost_point"`
	EstimatedCostLow   pgtype.Numeric     `json:"estimated_cost_low"`
	EstimatedCostHigh  pgtype.Numeric     `json:"estimated_cost_high"`
	CostConfidence     pgtype.Text        `json:"cost_confidence"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type GroceryListItem struct {
	ID             string         `json:"id"`
	GroceryListID  string         `json:"grocery_list_id"`
	IngredientID   string         `json:"ingredient_id"`
	DisplayName    string         `json:"display_name"`
	NeededQty      pgtype.Numeric `json:"needed_qty"`
	Unit           string         `json:"unit"`
	Packages       pgtype.Int4    `json:"packages"`
	PackageLabel   pgtype.Text    `json:"package_label"`
	EstimatedPrice pgtype.Numeric `json:"estimated_price"`
	PriceTier      pgtype.Int4    `json:"price_tier"`
	InPantry       bool           `json:"in_pantry"`
	IsChecked      bool           `json:"is_checked"`
	UsedBy         []string       `json:"used_by"`
}

type Ingredient struct {
	ID                 string             `json:"id"`
	DisplayName        string             `json:"display_name"`
	Aisle              string             `json:"aisle"`
	FoodGroup          string             `json:"food_group"`
	ParentIngredientID pgtype.Text        `json:"parent_ingredient_id"`
	PriceReferenceUnit string             `json:"price_reference_unit"`
	IsPantryStaple     bool               `json:"is_pantry_staple"`
	AssumedOnHand      bool               `json:"assumed_on_hand"`
	ContainsMeat       bool               `json:"contains_meat"`
	ContainsPoultry    bool               `json:"contains_poultry"`
	ContainsFish       bool               `json:"contains_fish"`
	ContainsShellfish  bool               `json:"contains_shellfish"`
	ContainsDairy      bool               `json:"contains_dairy"`
	ContainsEgg        bool               `json:"contains_egg"`
	ContainsGluten     bool               `json:"contains_gluten"`
	ContainsWheat      bool               `json:"contains_wheat"`
	ContainsSoy        bool               `json:"contains_soy"`
	ContainsPeanut     bool               `json:"contains_peanut"`
	ContainsTreeNut    bool               `json:"contains_tree_nut"`
	ContainsSesame     bool               `json:"contains_sesame"`
	ContainsCoconut    bool               `json:"contains_coconut"`
	IsAnimalDerived    bool               `json:"is_animal_derived"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type IngredientPrice struct {
	ID              string             `json:"id"`
	IngredientID    string             `json:"ingredient_id"`
	UnitPrice       pgtype.Numeric     `json:"unit_price"`
	PackageSize     pgtype.Numeric     `json:"package_size"`
	Divisible       bool               `json:"divisible"`
	Tier            int32              `json:"tier"`
	Source          string             `json:"source"`
	GeographicScope string             `json:"geographic_scope"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MealPlan struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	Status             string             `json:"status"`
	StartDate          pgtype.Date        `json:"start_date"`
	Days               int32              `json:"days"`
	HouseholdSize      int32              `json:"household_size"`
	Request            []byte             `json:"request"`
	BudgetAmount       pgtype.Numeric     `json:"budget_amount"`
	EstimatedCostPoint pgtype.Numeric     `json:"estimated_cost_point"`
	EstimatedCostLow   pgtype.Numeric     `json:"estimated_cost_low"`
	EstimatedCostHigh  pgtype.Numeric     `json:"estimated_cost_high"`
	CostConfidence     pgtype.Text        `json:"cost_confidence"`
	PennyMessage       string             `json:"penny_message"`
	Assumptions        []string           `json:"assumptions"`
	GenerationSource   string             `json:"generation_source"`
	GenerationVersion  string             `json:"generation_version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type MealPlanMeal struct {
	ID                  string         `json:"id"`
	MealPlanID          string         `json:"meal_plan_id"`
	Day                 int32          `json:"day"`
	MealType            string         `json:"meal_type"`
	RecipeID            string         `json:"recipe_id"`
	ScaleFactor         pgtype.Numeric `json:"scale_factor"`
	ServingsPlanned     pgtype.Numeric `json:"servings_planned"`
	PantryIngredientIds []string       `json:"pantry_ingredient_ids"`
	ConsumedCost        pgtype.Numeric `json:"consumed_cost"`
	Why                 pgtype.Text    `json:"why"`
}

type OnboardingState struct {
	UserID                 string             `json:"user_id"`
	HasCompletedOnboarding bool               `json:"has_completed_onboarding"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type PantryItem struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Name           string             `json:"name"`
	Quantity       string             `json:"quantity"`
	Location       string             `json:"location"`
	ExpirationDate pgtype.Date        `json:"expiration_date"`
	Category       string             `json:"category"`
	Status         string             `json:"status"`
	DateAdded      pgtype.Date        `json:"date_added"`
	DateUsed       pgtype.Date        `json:"date_used"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Preference struct {
	UserID                               string             `json:"user_id"`
	WeeklyBudget                         string             `json:"weekly_budget"`
	PreferredFinanceTopics               []string           `json:"preferred_finance_topics"`
	PreferredResources                   []string           `json:"preferred_resources"`
	WantsGovAssistance                   bool               `json:"wants_gov_assistance"`
	LastMealPlanDate                     pgtype.Date        `json:"last_meal_plan_date"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	NotificationsEnabled                 bool               `json:"notifications_enabled"`
	ExpiringPantryNotificationsEnabled   bool               `json:"expiring_pantry_notifications_enabled"`
	WeeklyMealPlanNotificationsEnabled   bool               `json:"weekly_meal_plan_notifications_enabled"`
	ResourceReminderNotificationsEnabled bool               `json:"resource_reminder_notifications_enabled"`
}

type Profile struct {
	UserID          string             `json:"user_id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Phone           string             `json:"phone"`
	Zip             string             `json:"zip"`
	HouseholdSize   int32              `json:"household_size"`
	ProfileImageUri pgtype.Text        `json:"profile_image_uri"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProfileHandle struct {
	Handle    string             `json:"handle"`
	UserID    string             `json:"user_id"`
	IsCurrent bool               `json:"is_current"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RetiredAt pgtype.Timestamptz `json:"retired_at"`
}

type PushToken struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Token      string             `json:"token"`
	Platform   string             `json:"platform"`
	DeviceID   pgtype.Text        `json:"device_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type Recipe struct {
	ID                   string             `json:"id"`
	OwnerUserID          pgtype.Text        `json:"owner_user_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	SourceType           string             `json:"source_type"`
	SourceUrl            pgtype.Text        `json:"source_url"`
	SourceName           pgtype.Text        `json:"source_name"`
	LicenseID            pgtype.Text        `json:"license_id"`
	AttributionText      pgtype.Text        `json:"attribution_text"`
	Visibility           string             `json:"visibility"`
	ReviewStatus         string             `json:"review_status"`
	Servings             pgtype.Numeric     `json:"servings"`
	ServingsConfidence   string             `json:"servings_confidence"`
	ServingSizeText      pgtype.Text        `json:"serving_size_text"`
	Scalable             bool               `json:"scalable"`
	PrepTimeMinutes      pgtype.Int4        `json:"prep_time_minutes"`
	CookTimeMinutes      pgtype.Int4        `json:"cook_time_minutes"`
	TotalTimeMinutes     pgtype.Int4        `json:"total_time_minutes"`
	TimeConfidence       string             `json:"time_confidence"`
	MealTypes            []string           `json:"meal_types"`
	Cuisine              pgtype.Text        `json:"cuisine"`
	Difficulty           pgtype.Int4        `json:"difficulty"`
	EquipmentRequired    []string           `json:"equipment_required"`
	IsComponent          bool               `json:"is_component"`
	Tags                 []string           `json:"tags"`
	CaloriesKcal         pgtype.Numeric     `json:"calories_kcal"`
	ProteinG             pgtype.Numeric     `json:"protein_g"`
	CarbsG               pgtype.Numeric     `json:"carbs_g"`
	FatG                 pgtype.Numeric     `json:"fat_g"`
	FiberG               pgtype.Numeric     `json:"fiber_g"`
	SodiumMg             pgtype.Numeric     `json:"sodium_mg"`
	NutritionBasis       pgtype.Text        `json:"nutrition_basis"`
	NutritionConfidence  pgtype.Text        `json:"nutrition_confidence"`
	BaseMealPlanEligible bool               `json:"base_meal_plan_eligible"`
	MissingInformation   []string           `json:"missing_information"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type RecipeIngredient struct {
	ID                 string         `json:"id"`
	RecipeID           string         `json:"recipe_id"`
	Position           int32          `json:"position"`
	RawText            string         `json:"raw_text"`
	IngredientID       pgtype.Text    `json:"ingredient_id"`
	DisplayName        pgtype.Text    `json:"display_name"`
	Quantity           pgtype.Numeric `json:"quantity"`
	Unit               pgtype.Text    `json:"unit"`
	Preparation        pgtype.Text    `json:"preparation"`
	Grams              pgtype.Numeric `json:"grams"`
	IsOptional         bool           `json:"is_optional"`
	IsToTaste          bool           `json:"is_to_taste"`
	MissingInformation pgtype.Text    `json:"missing_information"`
}

type RecipeInstruction struct {
	ID       string      `json:"id"`
	RecipeID string      `json:"recipe_id"`
	Step     int32       `json:"step"`
	Text     string      `json:"text"`
	Minutes  pgtype.Int4 `json:"minutes"`
}

type SavedRecipe struct {
	UserID    string             `json:"user_id"`
	RecipeID  string             `json:"recipe_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          string             `json:"id"`
	AuthSubject string             `json:"auth_subject"`
	Email       pgtype.Text        `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
