// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pantry.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPantryItem = `-- name: CreatePantryItem :one
INSERT INTO pantry_items (id, user_id, name, quantity, location, expiration_date, category, status, date_added)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'ACTIVE', $8)
RETURNING id, user_id, name, quantity, location, expiration_date, category, status, date_added, date_used, created_at, updated_at
`

type CreatePantryItemParams struct {
	ID             string      `json:"id"`
	UserID         string      `json:"user_id"`
	Name           string      `json:"name"`
	Quantity       string      `json:"quantity"`
	Location       string      `json:"location"`
	ExpirationDate pgtype.Date `json:"expiration_date"`
	Category       string      `json:"category"`
	DateAdded      pgtype.Date `json:"date_added"`
}

func (q *Queries) CreatePantryItem(ctx context.Context, arg CreatePantryItemParams) (PantryItem, error) {
	row := q.db.QueryRow(ctx, createPantryItem,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Quantity,
		arg.Location,
		arg.ExpirationDate,
		arg.Category,
		arg.DateAdded,
	)
	var i PantryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Quantity,
		&i.Location,
		&i.ExpirationDate,
		&i.Category,
		&i.Status,
		&i.DateAdded,
		&i.DateUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePantryItem = `-- name: DeletePantryItem :execrows
DELETE FROM pantry_items
WHERE id = $1 AND user_id = $2
`

type DeletePantryItemParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeletePantryItem(ctx context.Context, arg DeletePantryItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePantryItem, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPantryItemForUser = `-- name: GetPantryItemForUser :one
SELECT id, user_id, name, quantity, location, expiration_date, category, status, date_added, date_used, created_at, updated_at
FROM pantry_items
WHERE id = $1 AND user_id = $2
`

type GetPantryItemForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetPantryItemForUser(ctx context.Context, arg GetPantryItemForUserParams) (PantryItem, error) {
	row := q.db.QueryRow(ctx, getPantryItemForUser, arg.ID, arg.UserID)
	var i PantryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Quantity,
		&i.Location,
		&i.ExpirationDate,
		&i.Category,
		&i.Status,
		&i.DateAdded,
		&i.DateUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPantryItems = `-- name: ListPantryItems :many
SELECT id, user_id, name, quantity, location, expiration_date, category, status, date_added, date_used, created_at, updated_at
FROM pantry_items
WHERE user_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR location = $3)
ORDER BY expiration_date ASC, created_at ASC
`

type ListPantryItemsParams struct {
	UserID   string      `json:"user_id"`
	Status   pgtype.Text `json:"status"`
	Location pgtype.Text `json:"location"`
}

func (q *Queries) ListPantryItems(ctx context.Context, arg ListPantryItemsParams) ([]PantryItem, error) {
	rows, err := q.db.Query(ctx, listPantryItems, arg.UserID, arg.Status, arg.Location)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PantryItem{}
	for rows.Next() {
		var i PantryItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Quantity,
			&i.Location,
			&i.ExpirationDate,
			&i.Category,
			&i.Status,
			&i.DateAdded,
			&i.DateUsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPantryItemUsed = `-- name: MarkPantryItemUsed :one
UPDATE pantry_items
SET status = 'USED',
    date_used = COALESCE(date_used, CURRENT_DATE),
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, quantity, location, expiration_date, category, status, date_added, date_used, created_at, updated_at
`

type MarkPantryItemUsedParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) MarkPantryItemUsed(ctx context.Context, arg MarkPantryItemUsedParams) (PantryItem, error) {
	row := q.db.QueryRow(ctx, markPantryItemUsed, arg.ID, arg.UserID)
	var i PantryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Quantity,
		&i.Location,
		&i.ExpirationDate,
		&i.Category,
		&i.Status,
		&i.DateAdded,
		&i.DateUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pantryWasteStats = `-- name: PantryWasteStats :many
SELECT category, status, count(*)::int AS item_count
FROM pantry_items
WHERE user_id = $1
GROUP BY category, status
`

type PantryWasteStatsRow struct {
	Category  string `json:"category"`
	Status    string `json:"status"`
	ItemCount int32  `json:"item_count"`
}

func (q *Queries) PantryWasteStats(ctx context.Context, userID string) ([]PantryWasteStatsRow, error) {
	rows, err := q.db.Query(ctx, pantryWasteStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PantryWasteStatsRow{}
	for rows.Next() {
		var i PantryWasteStatsRow
		if err := rows.Scan(&i.Category, &i.Status, &i.ItemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePantryItem = `-- name: UpdatePantryItem :one
UPDATE pantry_items
SET name = COALESCE($1, name),
    quantity = COALESCE($2, quantity),
    location = COALESCE($3, location),
    expiration_date = COALESCE($4, expiration_date),
    category = COALESCE($5, category),
    status = COALESCE($6, status),
    date_used = CASE
      WHEN $6::text = 'USED' AND date_used IS NULL THEN CURRENT_DATE
      WHEN $6::text IS NOT NULL AND $6::text <> 'USED' THEN NULL
      ELSE date_used
    END,
    updated_at = now()
WHERE id = $7 AND user_id = $8
RETURNING id, user_id, name, quantity, location, expiration_date, category, status, date_added, date_used, created_at, updated_at
`

type UpdatePantryItemParams struct {
	Name           pgtype.Text `json:"name"`
	Quantity       pgtype.Text `json:"quantity"`
	Location       pgtype.Text `json:"location"`
	ExpirationDate pgtype.Date `json:"expiration_date"`
	Category       pgtype.Text `json:"category"`
	Status         pgtype.Text `json:"status"`
	ID             string      `json:"id"`
	UserID         string      `json:"user_id"`
}

func (q *Queries) UpdatePantryItem(ctx context.Context, arg UpdatePantryItemParams) (PantryItem, error) {
	row := q.db.QueryRow(ctx, updatePantryItem,
		arg.Name,
		arg.Quantity,
		arg.Location,
		arg.ExpirationDate,
		arg.Category,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	var i PantryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Quantity,
		&i.Location,
		&i.ExpirationDate,
		&i.Category,
		&i.Status,
		&i.DateAdded,
		&i.DateUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
