// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: push_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushToken = `-- name: DeletePushToken :execrows
DELETE FROM push_tokens
WHERE user_id = $1 AND token = $2
`

type DeletePushTokenParams struct {
	UserID string `json:"user_id"`
	Token  string `json:"token"`
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushToken, arg.UserID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPushToken = `-- name: UpsertPushToken :one
INSERT INTO push_tokens (id, user_id, token, platform, device_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    device_id = EXCLUDED.device_id,
    updated_at = now(),
    last_seen_at = now()
RETURNING id, user_id, token, platform, device_id, created_at, updated_at, last_seen_at
`

type UpsertPushTokenParams struct {
	ID       string      `json:"id"`
	UserID   string      `json:"user_id"`
	Token    string      `json:"token"`
	Platform string      `json:"platform"`
	DeviceID pgtype.Text `json:"device_id"`
}

func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) (PushToken, error) {
	row := q.db.QueryRow(ctx, upsertPushToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Platform,
		arg.DeviceID,
	)
	var i PushToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
