// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recipes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRecipeChildren = `-- name: DeleteRecipeChildren :exec
DELETE FROM recipe_ingredients WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeChildren(ctx context.Context, recipeID string) error {
	_, err := q.db.Exec(ctx, deleteRecipeChildren, recipeID)
	return err
}

const deleteRecipeInstructions = `-- name: DeleteRecipeInstructions :exec
DELETE FROM recipe_instructions WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeInstructions(ctx context.Context, recipeID string) error {
	_, err := q.db.Exec(ctx, deleteRecipeInstructions, recipeID)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, owner_user_id, title, description, source_type, source_url, source_name, license_id, attribution_text, visibility, review_status, servings, servings_confidence, serving_size_text, scalable, prep_time_minutes, cook_time_minutes, total_time_minutes, time_confidence, meal_types, cuisine, difficulty, equipment_required, is_component, tags, calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sodium_mg, nutrition_basis, nutrition_confidence, base_meal_plan_eligible, missing_information, created_at, updated_at FROM recipes
WHERE id = $1
  AND (owner_user_id IS NULL OR owner_user_id = $2)
`

type GetRecipeParams struct {
	ID     string      `json:"id"`
	UserID pgtype.Text `json:"user_id"`
}

// A recipe is readable when it is library content or owned by this user.
func (q *Queries) GetRecipe(ctx context.Context, arg GetRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipe, arg.ID, arg.UserID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.SourceType,
		&i.SourceUrl,
		&i.SourceName,
		&i.LicenseID,
		&i.AttributionText,
		&i.Visibility,
		&i.ReviewStatus,
		&i.Servings,
		&i.ServingsConfidence,
		&i.ServingSizeText,
		&i.Scalable,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.TotalTimeMinutes,
		&i.TimeConfidence,
		&i.MealTypes,
		&i.Cuisine,
		&i.Difficulty,
		&i.EquipmentRequired,
		&i.IsComponent,
		&i.Tags,
		&i.CaloriesKcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.SodiumMg,
		&i.NutritionBasis,
		&i.NutritionConfidence,
		&i.BaseMealPlanEligible,
		&i.MissingInformation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecipeIngredient = `-- name: InsertRecipeIngredient :exec
INSERT INTO recipe_ingredients (
  id, recipe_id, position, raw_text, ingredient_id, display_name, quantity,
  unit, preparation, grams, is_optional, is_to_taste, missing_information
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type InsertRecipeIngredientParams struct {
	ID                 string         `json:"id"`
	RecipeID           string         `json:"recipe_id"`
	Position           int32          `json:"position"`
	RawText            string         `json:"raw_text"`
	IngredientID       pgtype.Text    `json:"ingredient_id"`
	DisplayName        pgtype.Text    `json:"display_name"`
	Quantity           pgtype.Numeric `json:"quantity"`
	Unit               pgtype.Text    `json:"unit"`
	Preparation        pgtype.Text    `json:"preparation"`
	Grams              pgtype.Numeric `json:"grams"`
	IsOptional         bool           `json:"is_optional"`
	IsToTaste          bool           `json:"is_to_taste"`
	MissingInformation pgtype.Text    `json:"missing_information"`
}

func (q *Queries) InsertRecipeIngredient(ctx context.Context, arg InsertRecipeIngredientParams) error {
	_, err := q.db.Exec(ctx, insertRecipeIngredient,
		arg.ID,
		arg.RecipeID,
		arg.Position,
		arg.RawText,
		arg.IngredientID,
		arg.DisplayName,
		arg.Quantity,
		arg.Unit,
		arg.Preparation,
		arg.Grams,
		arg.IsOptional,
		arg.IsToTaste,
		arg.MissingInformation,
	)
	return err
}

const insertRecipeInstruction = `-- name: InsertRecipeInstruction :exec
INSERT INTO recipe_instructions (id, recipe_id, step, text, minutes)
VALUES ($1,$2,$3,$4,$5)
`

type InsertRecipeInstructionParams struct {
	ID       string      `json:"id"`
	RecipeID string      `json:"recipe_id"`
	Step     int32       `json:"step"`
	Text     string      `json:"text"`
	Minutes  pgtype.Int4 `json:"minutes"`
}

func (q *Queries) InsertRecipeInstruction(ctx context.Context, arg InsertRecipeInstructionParams) error {
	_, err := q.db.Exec(ctx, insertRecipeInstruction,
		arg.ID,
		arg.RecipeID,
		arg.Step,
		arg.Text,
		arg.Minutes,
	)
	return err
}

const listLibraryRecipes = `-- name: ListLibraryRecipes :many
SELECT id, owner_user_id, title, description, source_type, source_url, source_name, license_id, attribution_text, visibility, review_status, servings, servings_confidence, serving_size_text, scalable, prep_time_minutes, cook_time_minutes, total_time_minutes, time_confidence, meal_types, cuisine, difficulty, equipment_required, is_component, tags, calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sodium_mg, nutrition_basis, nutrition_confidence, base_meal_plan_eligible, missing_information, created_at, updated_at FROM recipes
WHERE owner_user_id IS NULL
  AND visibility = 'public'
  AND review_status = 'approved'
  AND ($1::text[] IS NULL OR tags @> $1::text[])
  AND ($2::text IS NULL OR $2::text = ANY(meal_types))
  AND ($3::text IS NULL OR title ILIKE '%' || $3::text || '%')
ORDER BY title ASC
`

type ListLibraryRecipesParams struct {
	Tags     []string    `json:"tags"`
	MealType pgtype.Text `json:"meal_type"`
	Search   pgtype.Text `json:"search"`
}

// Public, approved recipes. Tag filtering is AND across the supplied tags;
// meal_type narrows to recipes that declare it.
func (q *Queries) ListLibraryRecipes(ctx context.Context, arg ListLibraryRecipesParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listLibraryRecipes, arg.Tags, arg.MealType, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Description,
			&i.SourceType,
			&i.SourceUrl,
			&i.SourceName,
			&i.LicenseID,
			&i.AttributionText,
			&i.Visibility,
			&i.ReviewStatus,
			&i.Servings,
			&i.ServingsConfidence,
			&i.ServingSizeText,
			&i.Scalable,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.TotalTimeMinutes,
			&i.TimeConfidence,
			&i.MealTypes,
			&i.Cuisine,
			&i.Difficulty,
			&i.EquipmentRequired,
			&i.IsComponent,
			&i.Tags,
			&i.CaloriesKcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.FiberG,
			&i.SodiumMg,
			&i.NutritionBasis,
			&i.NutritionConfidence,
			&i.BaseMealPlanEligible,
			&i.MissingInformation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannableRecipes = `-- name: ListPlannableRecipes :many
SELECT id, owner_user_id, title, description, source_type, source_url, source_name, license_id, attribution_text, visibility, review_status, servings, servings_confidence, serving_size_text, scalable, prep_time_minutes, cook_time_minutes, total_time_minutes, time_confidence, meal_types, cuisine, difficulty, equipment_required, is_component, tags, calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sodium_mg, nutrition_basis, nutrition_confidence, base_meal_plan_eligible, missing_information, created_at, updated_at FROM recipes
WHERE base_meal_plan_eligible = true
  AND (
    (owner_user_id IS NULL AND visibility = 'public' AND review_status = 'approved')
    OR owner_user_id = $1
  )
`

// Everything the planner may draw from for this user: the approved library plus
// their own recipes. Incomplete recipes are excluded — viewable, never planned.
func (q *Queries) ListPlannableRecipes(ctx context.Context, userID pgtype.Text) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listPlannableRecipes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Description,
			&i.SourceType,
			&i.SourceUrl,
			&i.SourceName,
			&i.LicenseID,
			&i.AttributionText,
			&i.Visibility,
			&i.ReviewStatus,
			&i.Servings,
			&i.ServingsConfidence,
			&i.ServingSizeText,
			&i.Scalable,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.TotalTimeMinutes,
			&i.TimeConfidence,
			&i.MealTypes,
			&i.Cuisine,
			&i.Difficulty,
			&i.EquipmentRequired,
			&i.IsComponent,
			&i.Tags,
			&i.CaloriesKcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.FiberG,
			&i.SodiumMg,
			&i.NutritionBasis,
			&i.NutritionConfidence,
			&i.BaseMealPlanEligible,
			&i.MissingInformation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT id, recipe_id, position, raw_text, ingredient_id, display_name, quantity, unit, preparation, grams, is_optional, is_to_taste, missing_information FROM recipe_ingredients
WHERE recipe_id = ANY($1::text[])
ORDER BY recipe_id, position ASC
`

func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeIds []string) ([]RecipeIngredient, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeIngredient{}
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Position,
			&i.RawText,
			&i.IngredientID,
			&i.DisplayName,
			&i.Quantity,
			&i.Unit,
			&i.Preparation,
			&i.Grams,
			&i.IsOptional,
			&i.IsToTaste,
			&i.MissingInformation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeInstructions = `-- name: ListRecipeInstructions :many
SELECT id, recipe_id, step, text, minutes FROM recipe_instructions
WHERE recipe_id = ANY($1::text[])
ORDER BY recipe_id, step ASC
`

func (q *Queries) ListRecipeInstructions(ctx context.Context, recipeIds []string) ([]RecipeInstruction, error) {
	rows, err := q.db.Query(ctx, listRecipeInstructions, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeInstruction{}
	for rows.Next() {
		var i RecipeInstruction
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Step,
			&i.Text,
			&i.Minutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedRecipes = `-- name: ListSavedRecipes :many
SELECT r.id, r.owner_user_id, r.title, r.description, r.source_type, r.source_url, r.source_name, r.license_id, r.attribution_text, r.visibility, r.review_status, r.servings, r.servings_confidence, r.serving_size_text, r.scalable, r.prep_time_minutes, r.cook_time_minutes, r.total_time_minutes, r.time_confidence, r.meal_types, r.cuisine, r.difficulty, r.equipment_required, r.is_component, r.tags, r.calories_kcal, r.protein_g, r.carbs_g, r.fat_g, r.fiber_g, r.sodium_mg, r.nutrition_basis, r.nutrition_confidence, r.base_meal_plan_eligible, r.missing_information, r.created_at, r.updated_at FROM recipes r
JOIN saved_recipes s ON s.recipe_id = r.id
WHERE s.user_id = $1
ORDER BY s.created_at DESC
`

func (q *Queries) ListSavedRecipes(ctx context.Context, userID string) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listSavedRecipes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Description,
			&i.SourceType,
			&i.SourceUrl,
			&i.SourceName,
			&i.LicenseID,
			&i.AttributionText,
			&i.Visibility,
			&i.ReviewStatus,
			&i.Servings,
			&i.ServingsConfidence,
			&i.ServingSizeText,
			&i.Scalable,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.TotalTimeMinutes,
			&i.TimeConfidence,
			&i.MealTypes,
			&i.Cuisine,
			&i.Difficulty,
			&i.EquipmentRequired,
			&i.IsComponent,
			&i.Tags,
			&i.CaloriesKcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.FiberG,
			&i.SodiumMg,
			&i.NutritionBasis,
			&i.NutritionConfidence,
			&i.BaseMealPlanEligible,
			&i.MissingInformation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRecipeForUser = `-- name: SaveRecipeForUser :exec
INSERT INTO saved_recipes (user_id, recipe_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SaveRecipeForUserParams struct {
	UserID   string `json:"user_id"`
	RecipeID string `json:"recipe_id"`
}

func (q *Queries) SaveRecipeForUser(ctx context.Context, arg SaveRecipeForUserParams) error {
	_, err := q.db.Exec(ctx, saveRecipeForUser, arg.UserID, arg.RecipeID)
	return err
}

const unsaveRecipeForUser = `-- name: UnsaveRecipeForUser :exec
DELETE FROM saved_recipes WHERE user_id = $1 AND recipe_id = $2
`

type UnsaveRecipeForUserParams struct {
	UserID   string `json:"user_id"`
	RecipeID string `json:"recipe_id"`
}

func (q *Queries) UnsaveRecipeForUser(ctx context.Context, arg UnsaveRecipeForUserParams) error {
	_, err := q.db.Exec(ctx, unsaveRecipeForUser, arg.UserID, arg.RecipeID)
	return err
}

const upsertRecipe = `-- name: UpsertRecipe :one
INSERT INTO recipes (
  id, owner_user_id, title, description, source_type, source_url, source_name,
  license_id, attribution_text, visibility, review_status, servings,
  servings_confidence, serving_size_text, scalable, prep_time_minutes,
  cook_time_minutes, total_time_minutes, time_confidence, meal_types, cuisine,
  difficulty, equipment_required, is_component, tags, calories_kcal, protein_g,
  carbs_g, fat_g, fiber_g, sodium_mg, nutrition_basis, nutrition_confidence,
  base_meal_plan_eligible, missing_information
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,
  $22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  servings = EXCLUDED.servings,
  total_time_minutes = EXCLUDED.total_time_minutes,
  meal_types = EXCLUDED.meal_types,
  tags = EXCLUDED.tags,
  base_meal_plan_eligible = EXCLUDED.base_meal_plan_eligible,
  missing_information = EXCLUDED.missing_information,
  updated_at = now()
RETURNING id, owner_user_id, title, description, source_type, source_url, source_name, license_id, attribution_text, visibility, review_status, servings, servings_confidence, serving_size_text, scalable, prep_time_minutes, cook_time_minutes, total_time_minutes, time_confidence, meal_types, cuisine, difficulty, equipment_required, is_component, tags, calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sodium_mg, nutrition_basis, nutrition_confidence, base_meal_plan_eligible, missing_information, created_at, updated_at
`

type UpsertRecipeParams struct {
	ID                   string         `json:"id"`
	OwnerUserID          pgtype.Text    `json:"owner_user_id"`
	Title                string         `json:"title"`
	Description          pgtype.Text    `json:"description"`
	SourceType           string         `json:"source_type"`
	SourceUrl            pgtype.Text    `json:"source_url"`
	SourceName           pgtype.Text    `json:"source_name"`
	LicenseID            pgtype.Text    `json:"license_id"`
	AttributionText      pgtype.Text    `json:"attribution_text"`
	Visibility           string         `json:"visibility"`
	ReviewStatus         string         `json:"review_status"`
	Servings             pgtype.Numeric `json:"servings"`
	ServingsConfidence   string         `json:"servings_confidence"`
	ServingSizeText      pgtype.Text    `json:"serving_size_text"`
	Scalable             bool           `json:"scalable"`
	PrepTimeMinutes      pgtype.Int4    `json:"prep_time_minutes"`
	CookTimeMinutes      pgtype.Int4    `json:"cook_time_minutes"`
	TotalTimeMinutes     pgtype.Int4    `json:"total_time_minutes"`
	TimeConfidence       string         `json:"time_confidence"`
	MealTypes            []string       `json:"meal_types"`
	Cuisine              pgtype.Text    `json:"cuisine"`
	Difficulty           pgtype.Int4    `json:"difficulty"`
	EquipmentRequired    []string       `json:"equipment_required"`
	IsComponent          bool           `json:"is_component"`
	Tags                 []string       `json:"tags"`
	CaloriesKcal         pgtype.Numeric `json:"calories_kcal"`
	ProteinG             pgtype.Numeric `json:"protein_g"`
	CarbsG               pgtype.Numeric `json:"carbs_g"`
	FatG                 pgtype.Numeric `json:"fat_g"`
	FiberG               pgtype.Numeric `json:"fiber_g"`
	SodiumMg             pgtype.Numeric `json:"sodium_mg"`
	NutritionBasis       pgtype.Text    `json:"nutrition_basis"`
	NutritionConfidence  pgtype.Text    `json:"nutrition_confidence"`
	BaseMealPlanEligible bool           `json:"base_meal_plan_eligible"`
	MissingInformation   []string       `json:"missing_information"`
}

// Used by seeding and by recipe import. User recipes are forced private drafts
// by the service layer; only library content may be public.
func (q *Queries) UpsertRecipe(ctx context.Context, arg UpsertRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, upsertRecipe,
		arg.ID,
		arg.OwnerUserID,
		arg.Title,
		arg.Description,
		arg.SourceType,
		arg.SourceUrl,
		arg.SourceName,
		arg.LicenseID,
		arg.AttributionText,
		arg.Visibility,
		arg.ReviewStatus,
		arg.Servings,
		arg.ServingsConfidence,
		arg.ServingSizeText,
		arg.Scalable,
		arg.PrepTimeMinutes,
		arg.CookTimeMinutes,
		arg.TotalTimeMinutes,
		arg.TimeConfidence,
		arg.MealTypes,
		arg.Cuisine,
		arg.Difficulty,
		arg.EquipmentRequired,
		arg.IsComponent,
		arg.Tags,
		arg.CaloriesKcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.FiberG,
		arg.SodiumMg,
		arg.NutritionBasis,
		arg.NutritionConfidence,
		arg.BaseMealPlanEligible,
		arg.MissingInformation,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.SourceType,
		&i.SourceUrl,
		&i.SourceName,
		&i.LicenseID,
		&i.AttributionText,
		&i.Visibility,
		&i.ReviewStatus,
		&i.Servings,
		&i.ServingsConfidence,
		&i.ServingSizeText,
		&i.Scalable,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.TotalTimeMinutes,
		&i.TimeConfidence,
		&i.MealTypes,
		&i.Cuisine,
		&i.Difficulty,
		&i.EquipmentRequired,
		&i.IsComponent,
		&i.Tags,
		&i.CaloriesKcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.SodiumMg,
		&i.NutritionBasis,
		&i.NutritionConfidence,
		&i.BaseMealPlanEligible,
		&i.MissingInformation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
