// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOnboarding = `-- name: CompleteOnboarding :one
UPDATE onboarding_state
SET has_completed_onboarding = true,
    completed_at = now(),
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, has_completed_onboarding, completed_at, created_at, updated_at
`

func (q *Queries) CompleteOnboarding(ctx context.Context, userID string) (OnboardingState, error) {
	row := q.db.QueryRow(ctx, completeOnboarding, userID)
	var i OnboardingState
	err := row.Scan(
		&i.UserID,
		&i.HasCompletedOnboarding,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureOnboardingState = `-- name: EnsureOnboardingState :one
INSERT INTO onboarding_state (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE
SET user_id = EXCLUDED.user_id
RETURNING user_id, has_completed_onboarding, completed_at, created_at, updated_at
`

func (q *Queries) EnsureOnboardingState(ctx context.Context, userID string) (OnboardingState, error) {
	row := q.db.QueryRow(ctx, ensureOnboardingState, userID)
	var i OnboardingState
	err := row.Scan(
		&i.UserID,
		&i.HasCompletedOnboarding,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensurePreferences = `-- name: EnsurePreferences :one
INSERT INTO preferences (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE
SET user_id = EXCLUDED.user_id
RETURNING user_id, weekly_budget, preferred_finance_topics, preferred_resources, wants_gov_assistance, last_meal_plan_date,
  notifications_enabled, expiring_pantry_notifications_enabled, weekly_meal_plan_notifications_enabled,
  resource_reminder_notifications_enabled, created_at, updated_at
`

type EnsurePreferencesRow struct {
	UserID                               string             `json:"user_id"`
	WeeklyBudget                         string             `json:"weekly_budget"`
	PreferredFinanceTopics               []string           `json:"preferred_finance_topics"`
	PreferredResources                   []string           `json:"preferred_resources"`
	WantsGovAssistance                   bool               `json:"wants_gov_assistance"`
	LastMealPlanDate                     pgtype.Date        `json:"last_meal_plan_date"`
	NotificationsEnabled                 bool               `json:"notifications_enabled"`
	ExpiringPantryNotificationsEnabled   bool               `json:"expiring_pantry_notifications_enabled"`
	WeeklyMealPlanNotificationsEnabled   bool               `json:"weekly_meal_plan_notifications_enabled"`
	ResourceReminderNotificationsEnabled bool               `json:"resource_reminder_notifications_enabled"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) EnsurePreferences(ctx context.Context, userID string) (EnsurePreferencesRow, error) {
	row := q.db.QueryRow(ctx, ensurePreferences, userID)
	var i EnsurePreferencesRow
	err := row.Scan(
		&i.UserID,
		&i.WeeklyBudget,
		&i.PreferredFinanceTopics,
		&i.PreferredResources,
		&i.WantsGovAssistance,
		&i.LastMealPlanDate,
		&i.NotificationsEnabled,
		&i.ExpiringPantryNotificationsEnabled,
		&i.WeeklyMealPlanNotificationsEnabled,
		&i.ResourceReminderNotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureProfile = `-- name: EnsureProfile :one
INSERT INTO profiles (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE
SET user_id = EXCLUDED.user_id
RETURNING user_id, first_name, last_name, phone, zip, household_size, profile_image_uri, created_at, updated_at
`

func (q *Queries) EnsureProfile(ctx context.Context, userID string) (Profile, error) {
	row := q.db.QueryRow(ctx, ensureProfile, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Zip,
		&i.HouseholdSize,
		&i.ProfileImageUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth_subject, email, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePreferences = `-- name: UpdatePreferences :one
UPDATE preferences
SET weekly_budget = COALESCE($1, weekly_budget),
    preferred_finance_topics = COALESCE($2, preferred_finance_topics),
    preferred_resources = COALESCE($3, preferred_resources),
    wants_gov_assistance = COALESCE($4, wants_gov_assistance),
    last_meal_plan_date = COALESCE($5, last_meal_plan_date),
    notifications_enabled = COALESCE($6, notifications_enabled),
    expiring_pantry_notifications_enabled = COALESCE($7, expiring_pantry_notifications_enabled),
    weekly_meal_plan_notifications_enabled = COALESCE($8, weekly_meal_plan_notifications_enabled),
    resource_reminder_notifications_enabled = COALESCE($9, resource_reminder_notifications_enabled),
    updated_at = now()
WHERE user_id = $10
RETURNING user_id, weekly_budget, preferred_finance_topics, preferred_resources, wants_gov_assistance, last_meal_plan_date,
  notifications_enabled, expiring_pantry_notifications_enabled, weekly_meal_plan_notifications_enabled,
  resource_reminder_notifications_enabled, created_at, updated_at
`

type UpdatePreferencesParams struct {
	WeeklyBudget                         pgtype.Text `json:"weekly_budget"`
	PreferredFinanceTopics               []string    `json:"preferred_finance_topics"`
	PreferredResources                   []string    `json:"preferred_resources"`
	WantsGovAssistance                   pgtype.Bool `json:"wants_gov_assistance"`
	LastMealPlanDate                     pgtype.Date `json:"last_meal_plan_date"`
	NotificationsEnabled                 pgtype.Bool `json:"notifications_enabled"`
	ExpiringPantryNotificationsEnabled   pgtype.Bool `json:"expiring_pantry_notifications_enabled"`
	WeeklyMealPlanNotificationsEnabled   pgtype.Bool `json:"weekly_meal_plan_notifications_enabled"`
	ResourceReminderNotificationsEnabled pgtype.Bool `json:"resource_reminder_notifications_enabled"`
	UserID                               string      `json:"user_id"`
}

type UpdatePreferencesRow struct {
	UserID                               string             `json:"user_id"`
	WeeklyBudget                         string             `json:"weekly_budget"`
	PreferredFinanceTopics               []string           `json:"preferred_finance_topics"`
	PreferredResources                   []string           `json:"preferred_resources"`
	WantsGovAssistance                   bool               `json:"wants_gov_assistance"`
	LastMealPlanDate                     pgtype.Date        `json:"last_meal_plan_date"`
	NotificationsEnabled                 bool               `json:"notifications_enabled"`
	ExpiringPantryNotificationsEnabled   bool               `json:"expiring_pantry_notifications_enabled"`
	WeeklyMealPlanNotificationsEnabled   bool               `json:"weekly_meal_plan_notifications_enabled"`
	ResourceReminderNotificationsEnabled bool               `json:"resource_reminder_notifications_enabled"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (UpdatePreferencesRow, error) {
	row := q.db.QueryRow(ctx, updatePreferences,
		arg.WeeklyBudget,
		arg.PreferredFinanceTopics,
		arg.PreferredResources,
		arg.WantsGovAssistance,
		arg.LastMealPlanDate,
		arg.NotificationsEnabled,
		arg.ExpiringPantryNotificationsEnabled,
		arg.WeeklyMealPlanNotificationsEnabled,
		arg.ResourceReminderNotificationsEnabled,
		arg.UserID,
	)
	var i UpdatePreferencesRow
	err := row.Scan(
		&i.UserID,
		&i.WeeklyBudget,
		&i.PreferredFinanceTopics,
		&i.PreferredResources,
		&i.WantsGovAssistance,
		&i.LastMealPlanDate,
		&i.NotificationsEnabled,
		&i.ExpiringPantryNotificationsEnabled,
		&i.WeeklyMealPlanNotificationsEnabled,
		&i.ResourceReminderNotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    phone = COALESCE($3, phone),
    zip = COALESCE($4, zip),
    household_size = COALESCE($5, household_size),
    profile_image_uri = COALESCE($6, profile_image_uri),
    updated_at = now()
WHERE user_id = $7
RETURNING user_id, first_name, last_name, phone, zip, household_size, profile_image_uri, created_at, updated_at
`

type UpdateProfileParams struct {
	FirstName       pgtype.Text `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	Phone           pgtype.Text `json:"phone"`
	Zip             pgtype.Text `json:"zip"`
	HouseholdSize   pgtype.Int4 `json:"household_size"`
	ProfileImageUri pgtype.Text `json:"profile_image_uri"`
	UserID          string      `json:"user_id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Zip,
		arg.HouseholdSize,
		arg.ProfileImageUri,
		arg.UserID,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Zip,
		&i.HouseholdSize,
		&i.ProfileImageUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByAuthSubject = `-- name: UpsertUserByAuthSubject :one
INSERT INTO users (id, auth_subject, email)
VALUES ($1, $2, $3)
ON CONFLICT (auth_subject) DO UPDATE
SET email = COALESCE(EXCLUDED.email, users.email),
    updated_at = now()
RETURNING id, auth_subject, email, created_at, updated_at
`

type UpsertUserByAuthSubjectParams struct {
	ID          string      `json:"id"`
	AuthSubject string      `json:"auth_subject"`
	Email       pgtype.Text `json:"email"`
}

func (q *Queries) UpsertUserByAuthSubject(ctx context.Context, arg UpsertUserByAuthSubjectParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByAuthSubject, arg.ID, arg.AuthSubject, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
